(in-package :ww)
(stage backtracking-heuristic)

(defun bt-heuristic-state-signature (state)
  (list (copy-idb (problem-state.idb state))
        (problem-state.name state) (problem-state.time state)
        (problem-state.value state) (problem-state.heuristic state)
        (copy-tree (problem-state.instantiations state))))

(defun test-backtracking-heuristic-case (mode)
  (let ((*algorithm* 'backtracking)
        (*threads* 0)
        (*solution-type* (if (member mode '(:every :recursive)) 'every 'first))
        (saved-goal (symbol-function 'goal-fn))
        (saved-hook (and (fboundp 'heuristic?) (symbol-function 'heuristic?)))
        (saved-constraint (and (fboundp 'constraint-fn)
                               (symbol-function 'constraint-fn)))
        (calls 0)
        (failed nil))
    (unwind-protect
        (progn
          (fmakunbound 'heuristic?)
          (unless (eq mode :absent)
            (setf (symbol-function 'heuristic?)
                  (lambda (state)
                    (incf calls)
                    (when (eq mode :error) (error "TEST-HEURISTIC-ERROR"))
                    (when (eq (problem-state.name state) 'parameter-choice)
                      (assert (= (first (problem-state.instantiations state))
                                 (problem-state.value state))))
                    (if (eq mode :ties) 0 (problem-state.value state)))))
          (when (eq mode :constraint)
            (setf (symbol-function 'constraint-fn)
                  (lambda (state) (plusp (problem-state.value state)))))
          (when (eq mode :recursive)
            (setf (symbol-function 'goal-fn)
                  (lambda (state)
                    (member '(finished) (list-database (problem-state.idb state))
                            :test #'equal))))
          (handler-case (solve)
            (error (condition)
              (unless (and (eq mode :error)
                           (search "TEST-HEURISTIC-ERROR" (princ-to-string condition)))
                (error condition))
              (setf failed t)))
          (assert (equalp (bt-heuristic-state-signature *start-state*)
                          (bt-heuristic-state-signature *backtrack-state*)))
          (assert (null *choice-stack*))
          (ecase mode
            (:recursive
             (assert (= calls 10))
             (assert (= (length *solution-paths*) 5))
             (assert (every (lambda (solution) (= (solution.depth solution) 2))
                            *solution-paths*)))
            (:error (assert failed) (assert (null *solution-paths*)))
            (:absent (assert (zerop calls))
                     (assert (= 1 (solution.value (first *solution-paths*)))))
            (:ties (assert (= calls 5))
                   (assert (= 1 (solution.value (first *solution-paths*)))))
            (:ordered (assert (= calls 5))
                      (assert (= 0 (solution.value (first *solution-paths*)))))
            (:constraint (assert (= calls 4))
                         (assert (= 1 (solution.value (first *solution-paths*)))))
            (:every (assert (= calls 5))
                    (assert (equal '(0 1 2 4 5)
                                   (reverse (mapcar #'solution.value *solution-paths*)))))))
      (setf (symbol-function 'goal-fn) saved-goal)
      (if saved-hook (setf (symbol-function 'heuristic?) saved-hook)
          (fmakunbound 'heuristic?))
      (if saved-constraint (setf (symbol-function 'constraint-fn) saved-constraint)
          (fmakunbound 'constraint-fn)))))

(defun test-backtracking-heuristic-snapshot ()
  (let* ((*backtrack-state* (copy-problem-state *start-state*))
         (*choice-stack* nil)
         (action (first *actions*))
         (choice (make-choice :act (list (action.name action) 17)
                              :value 17
                              :forward-update (copy-idb (problem-state.idb *start-state*))
                              :inverse-update (copy-idb (problem-state.idb *start-state*))))
         (saved-hook (and (fboundp 'heuristic?) (symbol-function 'heuristic?))))
    (unwind-protect
        (progn
          (setf (symbol-function 'heuristic?)
                (lambda (state)
                  (assert (= (problem-state.time state) (action.duration action)))
                  (assert (equal '(17) (problem-state.instantiations state)))
                  (problem-state.value state)))
          (assert (= 17 (score-choice-bt choice action 0)))
          (assert (null *choice-stack*))
          (assert (equalp (bt-heuristic-state-signature *start-state*)
                          (bt-heuristic-state-signature *backtrack-state*))))
      (if saved-hook (setf (symbol-function 'heuristic?) saved-hook)
          (fmakunbound 'heuristic?)))))

(defun test-backtracking-heuristic ()
  (dolist (mode '(:absent :ordered :ties :constraint :every :recursive :error))
    (test-backtracking-heuristic-case mode))
  (test-backtracking-heuristic-snapshot)
  (format t "~&BACKTRACKING-HEURISTIC-CHECKS-PASSED~%"))
