;;; Focused replay regression. Load after Quickloading Wouldwork.
(in-package :ww)
(stage crelay-topo)
(defparameter *crelay-replay-test-actions* '(  (START-RECORDER AGENT1)
  (MOVE AGENT1* ((WALK LOCATION1 NIL LOCATION2)))
  (MOVE AGENT1* ((STEP (LOCATION2 GROUND) NIL
                                  (LOCATION2 PLATE1))))
  (MOVE AGENT1 ((WALK LOCATION1 (GATE1 GATE3) LOCATION9)))
  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION9)
  (MOVE AGENT1 ((WALK LOCATION9 (GATE1 GATE3) LOCATION2)))
  (PUT-CONNECTOR AGENT1 CONNECTOR1 LOCATION2 PLATE1)
  (MOVE AGENT1* ((STEP (LOCATION2 PLATE1) NIL
                                  (LOCATION2 GROUND))))
  (MOVE AGENT1* ((WALK LOCATION2 NIL LOCATION1)))
  (STOP-RECORDER AGENT1*)


  (MOVE AGENT1 ((WALK LOCATION2 NIL LOCATION1)))
  (START-RECORDER AGENT1)
  (MOVE AGENT1* ((WALK LOCATION1 (GATE1) LOCATION7)))
  (PICKUP-TRAY AGENT1* TRAY1* LOCATION7 LOCATION7)
  (MOVE AGENT1* ((WALK LOCATION7 NIL LOCATION5)))
  (MOVE AGENT1 ((WALK LOCATION1 (GATE1) LOCATION4)))
  (MOVE AGENT1 ((STEP (LOCATION4 GROUND) NIL
                                  (LOCATION4 BLOWER1))))
  (TOGGLE-SWITCH AGENT1 SWITCH1)
  (MOVE AGENT1 ((JUMP (LOCATION20 GROUND) NIL
                                  (LOCATION5 TRAY1*))))
  (TOGGLE-SWITCH AGENT1 SWITCH1)
  (MOVE AGENT1 ((JUMP (LOCATION5 TRAY1*) (GATE2)
                                  (LOCATION6 GROUND))))
  (PICKUP-BOX AGENT1 BOX1 LOCATION6 LOCATION6)
  (MOVE AGENT1 ((JUMP LOCATION6 (GATE2) LOCATION4)
                     (WALK LOCATION4 NIL LOCATION5)))
  (PUT-BOX AGENT1 BOX1 GROUND LOCATION5)
  (MOVE AGENT1* ((WALK LOCATION5 (GATE1) LOCATION1)))
  (PUT-TRAY AGENT1* TRAY1* GROUND LOCATION1)
  (STOP-RECORDER AGENT1*)

))
(defun test-crelay-route-replay ()
  (let* ((prefix (validate-action-sequence *start-state*
                   (subseq *crelay-replay-test-actions* 0 22)))
         (state (action-sequence-validation-final-state prefix))
         (before (list-database (problem-state.idb state)))
         (canonical (movement-results-in-state state 'agent1 '(location6 ground)))
         (result (validate-action-sequence *start-state* *crelay-replay-test-actions*))
         (endpoint (action-sequence-validation-final-state result)))
    (assert (action-sequence-validation-success-p prefix))
    (assert (action-sequence-validation-success-p result))
    (assert (= 27 (problem-state.time endpoint)))
    (dolist (fact '((has-location box1 location5) (has-location agent1 location5)
                    (on connector1 plate1) (on tray1 plate2)
                    (recorder-cycle-stopped-by-ghost) (recorder-cycles-used 2)))
      (assert (member fact (list-database (problem-state.idb endpoint)) :test #'equal)))
    (assert (not (member '((location5 ground)
                          ((jump location6 (gate2) location4) (walk location4 nil location5)))
                        canonical :test #'equal)))
    (dolist (route '(((jump location6 (gate2) location4) (walk location2 nil location5))
                     ((jump location6 nil location4) (walk location4 nil location5))
                     ((walk location6 nil location19))
                     ((jump (location6 ground) (gate2) (location5 tray1*))
                      (walk location5 nil location4))
                     nil))
      (multiple-value-bind (new-state success reason)
          (apply-action-to-state (list 'move 'agent1 route) state nil)
        (declare (ignore new-state reason))
        (assert (not success))))
    (assert (equal before (list-database (problem-state.idb state))))
    (assert (null *replay-action*))
    (multiple-value-bind (new-state success reason)
        (apply-action-to-state
          '(move agent1 ((walk location1 (gate1) location4))) *start-state* nil)
      (declare (ignore new-state reason))
      (assert (not success)))
    (assert (equal canonical (movement-results-in-state state 'agent1 '(location6 ground))))
    (format t "~%CRELAY-ROUTE-REPLAY-REGRESSIONS: PASS~%")))
(test-crelay-route-replay)
(eval (cons 'validate-solution *crelay-replay-test-actions*))
