;;;; PERGATORY VIDEO SOLUTION phase 3, around the corner
(pickup-connector agent1 connector1 area1)
(connect-to-2-terminus agent1 connector1 transmitter1 receiver1 area1 ground)
(move agent1 area1 area2)
(pickup-connector agent1 connector2 area2)
(move agent1 area2 area4)
(connect-to-1-terminus agent1 connector2 transmitter1 area4 ground)
(move agent1 area4 area1)
(pickup-connector agent1 connector1 area1)
(move agent1 area1 area2)
(connect-to-3-terminus agent1 connector1 transmitter2 receiver1 receiver3 area2 ground)
(move agent1 area2 area3)
(pickup-connector agent1 connector3 area3)
(connect-to-3-terminus agent1 connector3 transmitter1 connector1 receiver2 area3 ground)
(move agent1 area3 area4)
(pickup-connector agent1 connector2 area4)
