;;; Generation and restoration checks for incremental and snapshot effects.
(in-package :ww)
(stage backtracking-heuristic)
(ww-set *algorithm* backtracking)

(defun bt-update-test-signature (state)
  (list (copy-idb (problem-state.idb state))
        (problem-state.name state) (problem-state.time state)
        (problem-state.value state) (problem-state.heuristic state)
        (copy-tree (problem-state.instantiations state))))

(defun bt-update-test-snapshots (state)
  "Follow the enumeration effect contract: change copies, not STATE."
  (loop for value in '(17 23)
        append (let ((child (copy-state state)))
                 (revise (problem-state.idb child) '((not (ready)) (done)))
                 (let ((updates (make-update-from child (list value))))
                   (setf (update.value (first updates)) value)
                   updates))))

(defun bt-update-test-child ()
  "Exercise an incremental descendant beneath a snapshot choice."
  (let* ((action (find 'finish-choice *actions* :key #'action.name))
         (before (bt-update-test-signature *backtrack-state*))
         (choice (first (generate-choices-for-single-combination-bt action nil t 1))))
    (assert (choice.pre-applied-p choice))
    (assert (not (equalp (first before) (problem-state.idb *backtrack-state*))))
    (assert (register-choice-bt choice action 1 nil))
    (undo-choice-bt choice action 1 nil)
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))))

(defun test-backtracking-snapshot-generation (reject-p)
  (let* ((*backtrack-state* (copy-problem-state *start-state*))
         (*choice-stack* nil)
         (before (bt-update-test-signature *backtrack-state*))
         (action (make-action :name 'snapshot-test :duration 2
                              :eff-defun-name 'bt-update-test-snapshots))
         (choices (generate-choices-for-single-combination-bt action nil t 0))
         (saved-constraint (and (fboundp 'constraint-fn)
                                (symbol-function 'constraint-fn))))
    (unwind-protect
        (progn
          (assert (= 2 (length choices)))
          (assert (equalp before (bt-update-test-signature *backtrack-state*)))
          (setf (symbol-function 'constraint-fn)
                (lambda (state) (declare (ignore state)) (not reject-p)))
          (dolist (choice choices)
            (let ((snapshot (copy-idb (choice.forward-update choice))))
              (assert (not (equalp snapshot (first before))))
              (assert (eql (not reject-p) (register-choice-bt choice action 0 nil)))
              (unless reject-p
                (assert (= 2 (problem-state.time *backtrack-state*)))
                (assert (equalp snapshot (problem-state.idb *backtrack-state*)))
                (assert (= (choice.value choice) (problem-state.value *backtrack-state*)))
                (bt-update-test-child)
                (undo-choice-bt choice action 0 nil))
              (assert (equalp snapshot (choice.forward-update choice)))
              (assert (equalp (first before) (choice.inverse-update choice)))
              (assert (equalp before (bt-update-test-signature *backtrack-state*)))
              (assert (null *choice-stack*)))))
      (if saved-constraint
          (setf (symbol-function 'constraint-fn) saved-constraint)
          (fmakunbound 'constraint-fn)))))

(defun test-backtracking-incremental-generation ()
  (let* ((*backtrack-state* (copy-problem-state *start-state*))
         (*choice-stack* nil)
         (before (bt-update-test-signature *backtrack-state*))
         (action (find 'later-choice *actions* :key #'action.name))
         (choice (first (generate-choices-for-single-combination-bt action nil t 0))))
    (assert (choice.pre-applied-p choice))
    (assert (not (equalp (first before) (problem-state.idb *backtrack-state*))))
    (assert (register-choice-bt choice action 0 nil))
    (undo-choice-bt choice action 0 nil)
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))
    (assert (null *choice-stack*))))

(defun test-bt-entry-restoration ()
  (dolist (hash-mode '(nil :standard :split))
    (let* ((db (make-hash-table))
           (*idb-hash-acc* (when (eq hash-mode :standard) 0))
           (*fixed-idb-hash-acc* (when (eq hash-mode :split) 0))
           (*symmetry-idb-acc* (when (eq hash-mode :split) (make-hash-table)))
           (*symmetry-idb-touched-p* nil)
           (*object-to-symmetry-membership* (make-hash-table :test #'eq))
           (*detect-propagated-changes* t)
           (*propagated-state-changed* nil))
      (setf (gethash 'ready *object-to-symmetry-membership*) t)
      (fold-store 1 nil db t)
      (let ((before (copy-idb db))
            (hash-before *idb-hash-acc*) (fixed-before *fixed-idb-hash-acc*)
            (frame (begin-bt-undo db)))
        (let ((*bt-undo-frame* frame))
          (add-int-prop-key db 1 '(ready))
          (add-int-prop-key db 1 '(done))
          (del-int-prop-key db 2)
          (add-int-prop-key db 2 t)
          (add-int-prop-key db 2 t)
          (del-int-prop-key db 1))
        (restore-bt-undo frame)
        (assert (equalp before db))
        (assert (nth-value 1 (gethash 1 db)))
        (assert (eql hash-before *idb-hash-acc*))
        (assert (eql fixed-before *fixed-idb-hash-acc*))
        (when *symmetry-idb-acc* (assert (zerop (hash-table-count *symmetry-idb-acc*))))
        (assert (null *propagated-state-changed*))
        (assert (null *symmetry-idb-touched-p*))
        (assert (null (bt-undo-frame.head frame)))))))

(defun test-bt-expanded-restoration ()
  "Exercise physical expansion using isolated relation metadata and known symbols."
  (let ((saved (list *symmetrics* *bijective-relations* *complements*
                     *fluent-relation-indices* *static-db*)))
    (unwind-protect
        (progn
          (setf *symmetrics* (make-hash-table :test #'eq)
                *bijective-relations* (make-hash-table :test #'eq)
                *complements* (make-hash-table :test #'eq)
                *fluent-relation-indices* (make-hash-table :test #'eq)
                *static-db* (make-hash-table :test #'equal))
          (run-bt-expanded-restoration))
      (setf (values *symmetrics* *bijective-relations* *complements*
                    *fluent-relation-indices* *static-db*)
            (values-list saved)))))

(defun run-bt-expanded-restoration ()
    (dolist (mode '(:symmetric :bijective :complement :static))
      (clrhash *symmetrics*) (clrhash *bijective-relations*)
      (clrhash *complements*) (clrhash *fluent-relation-indices*)
      (clrhash *static-db*)
      (let ((db (make-hash-table)))
        (ecase mode
          (:symmetric (setf (gethash 'ready *symmetrics*) '((0 1)))
                      (add-prop '(ready 1 2) db t))
          (:bijective (setf (gethash 'ready *bijective-relations*) '(done finished)
                            (gethash 'done *fluent-relation-indices*) '(2)
                            (gethash 'finished *fluent-relation-indices*) '(1))
                      (add-proposition '(ready 1 1) db)
                      (add-proposition '(ready 2 2) db))
          (:complement (setf (gethash 'ready *complements*)
                             '((ready ?x) (not (done ?x)))))
          (:static (add-proposition '(ready) *static-db*)))
        (let ((before (copy-idb db)) (static-before (copy-idb *static-db*))
              (frame (begin-bt-undo db)))
          (let ((*bt-undo-frame* frame))
            (ecase mode
              ((:symmetric :bijective) (add-proposition '(ready 1 2) db))
              (:complement (delete-proposition '(ready 1) db))
              (:static (delete-proposition '(ready) *static-db*)
                       (add-proposition '(done) *static-db*))))
          (assert (or (not (equalp before db)) (not (equalp static-before *static-db*)))
                  () "Expansion test did not change the database: ~S" mode)
          (unless (eq mode :static)
            (assert (equalp before (bt-scratch-parent (copy-idb db) (make-choice :undo-frame frame)))))
          (restore-bt-undo frame)
          (assert (equalp before db))
          (assert (equalp static-before *static-db*))))))

(defun bt-update-test-error (state)
  (update-bt (problem-state.idb state) '(not (ready)))
  (error "BT-PARTIAL-EFFECT-ERROR"))

(defun test-bt-effect-error-restoration ()
  (let* ((*backtrack-state* (copy-problem-state *start-state*))
         (before (bt-update-test-signature *backtrack-state*))
         (action (make-action :name 'partial-error :eff-defun-name 'bt-update-test-error))
         (failed nil))
    (handler-case (generate-choices-for-single-combination-bt action nil t 0)
      (error (e) (assert (search "BT-PARTIAL-EFFECT-ERROR" (princ-to-string e))) (setf failed t)))
    (assert failed)
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))))

(defun test-bt-constraint-error-restoration ()
  (let* ((*backtrack-state* (copy-problem-state *start-state*)) (*choice-stack* nil)
         (before (bt-update-test-signature *backtrack-state*))
         (action (find 'later-choice *actions* :key #'action.name))
         (choice (first (generate-choices-for-single-combination-bt action nil t 0)))
         (old (and (fboundp 'constraint-fn) (symbol-function 'constraint-fn))) (failed nil))
    (unwind-protect
        (progn
          (setf (symbol-function 'constraint-fn)
                (lambda (state) (declare (ignore state)) (error "BT-CONSTRAINT-ERROR")))
          (handler-case (register-choice-bt choice action 0 nil)
            (error (e) (assert (search "BT-CONSTRAINT-ERROR" (princ-to-string e))) (setf failed t))))
      (if old (setf (symbol-function 'constraint-fn) old) (fmakunbound 'constraint-fn)))
    (assert failed) (assert (null *choice-stack*))
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))))

(defun test-bt-overlapping-siblings ()
  (let* ((*backtrack-state* (copy-problem-state *start-state*)) (*choice-stack* nil)
         (before (bt-update-test-signature *backtrack-state*))
         (action (find 'multiple-choices *actions* :key #'action.name))
         (choices (generate-choices-for-single-combination-bt action nil t 0)))
    (assert (= 2 (length choices)))
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))
    (dolist (choice choices)
      (assert (register-choice-bt choice action 0 nil))
      (undo-choice-bt choice action 0 nil)
      (assert (null (choice.undo-frame choice)))
      (assert (equalp before (bt-update-test-signature *backtrack-state*))))))

(defun test-bt-reapplication-error-restoration ()
  "An invalid second literal must not leave the first write installed."
  (let* ((*backtrack-state* (copy-problem-state *start-state*)) (*choice-stack* nil)
         (before (bt-update-test-signature *backtrack-state*))
         (action (find 'later-choice *actions* :key #'action.name))
         (choice (make-choice :forward-update '((not (ready)) invalid-literal)))
         (failed nil))
    (handler-case (register-choice-bt choice action 0 nil)
      (type-error () (setf failed t)))
    (assert failed)
    (assert (null *choice-stack*))
    (assert (null (choice.undo-frame choice)))
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))
    (assert (eq :uncached (problem-state.canonical-symmetry-form *backtrack-state*)))
    (assert (null (problem-state.idb-hash *backtrack-state*)))))

(defun bt-test-reference-set-signature (ops)
  "Original hash-table implementation, retained as a differential oracle."
  (let ((seen (make-hash-table :test #'equal))
        (unique-count 0) (xor-hash 0) (sum-hash 0))
    (dolist (op ops)
      (unless (gethash op seen)
        (setf (gethash op seen) t)
        (incf unique-count)
        (let ((h (sxhash op)))
          (setf xor-hash (logxor xor-hash h))
          (incf sum-hash h))))
    (list unique-count xor-hash sum-hash)))

(defun check-bt-set-signature (ops)
  (let ((before (copy-tree ops))
        (expected (bt-test-reference-set-signature ops)))
    (assert (equal expected (update-set-signature ops)))
    (assert (equal before ops))
    (assert (equal expected (update-set-signature (reverse ops))))
    (assert (equal expected (update-set-signature (append ops (copy-tree ops)))))))

(defun test-bt-set-signatures ()
  (dolist (ops '(nil ((ready)) ((not (ready))) ((peg-count 7))
                ((ready) (not (done)) (peg-count 7) (ready))))
    (check-bt-set-signature (copy-tree ops)))
  (dolist (size '(7 8 9 32))
    (let ((ops (loop for i below size collect (list 'peg-count i))))
      (check-bt-set-signature ops)
      ;; Equal but separately allocated literals straddle the cutoff cases.
      (setf (car (last ops)) (copy-tree (first ops)))
      (check-bt-set-signature ops)))
  (let ((literals '((ready) (not (done)) (peg-count 7))))
    (loop for size from 0 to 5 do
      (loop for code below (expt 3 size) do
        (check-bt-set-signature
          (loop for i below size
                collect (copy-tree (nth (mod (floor code (expt 3 i)) 3) literals)))))))
  (assert (equal '(0 0 0) (update-set-signature nil)))
  (format t "~&BACKTRACKING-SIGNATURE-CHECKS-PASSED~%"))

(defun test-bt-signature-cycle-check ()
  (let* ((*problem-type* 'planning)
         (inverse '((ready) (not (done)) (peg-count 7)))
         (forward (append (reverse (copy-tree inverse)) (list (copy-tree (first inverse)))))
         (signature (update-set-signature inverse))
         (*choice-stack* (list (make-choice :inverse-update inverse :inverse-sig signature)))
         (choice (make-choice :forward-update forward :forward-sig (update-set-signature forward))))
    (assert (detect-path-cycle choice))
    (let ((*problem-type* 'csp)) (assert (null (detect-path-cycle choice))))
    (setf (choice.forward-update choice) '((different))
          (choice.forward-sig choice) (update-set-signature '((different))))
    (assert (null (detect-path-cycle choice)))
    ;; A manufactured signature collision must still fail exact set comparison.
    (setf (choice.forward-sig choice) signature)
    (assert (null (detect-path-cycle choice))))
  (format t "~&BACKTRACKING-SIGNATURE-CYCLE-CHECKS-PASSED~%"))

(defvar *bt-path-test-goal* 'g)
(defvar *bt-path-test-snapshot-from* nil)
(defvar *bt-path-test-original-search*)
(defparameter *bt-path-test-nodes*
  '((a ready) (b done) (c finished) (d ready done) (g ready finished)))

(defun bt-path-test-facts (node)
  (mapcar #'list (cdr (assoc node *bt-path-test-nodes*))))

(defun bt-path-test-node (state)
  (let ((facts (loop for name in '(ready done finished)
                     when (gethash (convert-to-integer-memoized (list name))
                                   (problem-state.idb state)) collect name)))
    (car (find facts *bt-path-test-nodes* :key #'cdr :test #'equal))))

(defun bt-path-test-pre (state from to)
  (when (eq from (bt-path-test-node state)) (list from to)))

(defun bt-path-test-effect (state from to)
  (let* ((snapshot-p (eq from *bt-path-test-snapshot-from*))
         (db (if snapshot-p (copy-idb (problem-state.idb state)) (problem-state.idb state)))
         (ops (append (mapcar (lambda (fact) (list 'not fact)) (bt-path-test-facts from))
                      (bt-path-test-facts to)))
         (inverse nil))
    (dolist (op ops)
      (push (nth-value 1 (update-bt db op)) inverse))
    (list (make-update :changes (if snapshot-p db (list ops inverse))
                       :instantiations (list from to)))))

(defun bt-path-test-goal (state)
  ;; The time condition deliberately exercises goal-first ordering on a root repeat.
  (and (plusp (problem-state.time state))
       (eq *bt-path-test-goal* (bt-path-test-node state))))

(defun bt-path-test-audit-search ()
  (let ((before (bt-update-test-signature *start-state*)))
    (unwind-protect (funcall *bt-path-test-original-search*)
      (assert (equalp before (bt-update-test-signature *backtrack-state*)))
      (assert (null *choice-stack*))
      (assert (null *bt-path-fingerprints*))
      (assert (null *bt-path-search-active*)))))

(defun bt-path-test-run (edges expected-goals expected-repeats &key heuristic
                          (goal 'g) snapshot (mode 'path) (solution-type 'count) failure)
  (let* ((*bt-cycle-check* mode) (*algorithm* 'backtracking) (*problem-type* 'planning)
         (*tree-or-graph* 'tree) (*threads* 0) (*solution-type* solution-type)
         (*depth-cutoff* 5) (*debug* 0) (*probe* nil) (*bt-path-test-goal* goal)
         (*bt-path-test-snapshot-from* snapshot)
         (*bt-path-test-original-search* (symbol-function 'search-backtracking))
         (saved-actions *actions*)
         (hooks '(goal-fn heuristic? constraint-fn search-backtracking bt-scratch-parent))
         (saved (mapcar (lambda (name) (cons name (and (fboundp name) (symbol-function name)))) hooks)))
    (unwind-protect
        (progn
          (setf *actions* (list (make-action :name 'path-step :duration 1
                                  :precondition-args edges :pre-defun-name 'bt-path-test-pre
                                  :eff-defun-name 'bt-path-test-effect))
                (symbol-function 'goal-fn) #'bt-path-test-goal
                (symbol-function 'search-backtracking) #'bt-path-test-audit-search)
          (fmakunbound 'heuristic?) (fmakunbound 'constraint-fn)
          (when heuristic (setf (symbol-function 'heuristic?) (lambda (state) (declare (ignore state)) 0)))
          (case failure
            (:score (setf (symbol-function 'heuristic?)
                          (lambda (state) (declare (ignore state)) (error "BT-PATH-SCORE-ERROR"))))
            (:verify (setf (symbol-function 'bt-scratch-parent)
                           (lambda (&rest args) (declare (ignore args)) (error "BT-PATH-VERIFY-ERROR"))))
            (:constraint (setf (symbol-function 'constraint-fn)
                               (lambda (state) (declare (ignore state)) nil))))
          (let ((*standard-output* (make-broadcast-stream)) (*trace-output* (make-broadcast-stream)))
            (if (member failure '(:score :verify))
                (let ((caught nil))
                  (handler-case (solve)
                    (error (e) (assert (search (if (eq failure :score) "BT-PATH-SCORE-ERROR" "BT-PATH-VERIFY-ERROR")
                                              (princ-to-string e))) (setf caught t)))
                  (assert caught))
                (progn
                  (solve)
                  (assert (= expected-goals (if (eq solution-type 'count) *solution-count* (length *solution-paths*))))))
            (assert (= expected-repeats *repeated-states*))))
      (setf *actions* saved-actions)
      (dolist (entry saved)
        (if (cdr entry) (setf (symbol-function (car entry)) (cdr entry)) (fmakunbound (car entry)))))))

(defun test-bt-path-search ()
  (dolist (heuristic '(nil t))
    (bt-path-test-run '((a b) (b c) (c a)) 0 1 :heuristic heuristic)
    (bt-path-test-run '((a b) (b c) (c a)) 0 0 :heuristic heuristic :mode 'immediate)
    (bt-path-test-run '((a b) (b c) (c d) (d b)) 0 1 :heuristic heuristic)
    (bt-path-test-run '((a a)) 0 1 :heuristic heuristic)
    (bt-path-test-run '((a b) (a c) (b d) (c d) (d g)) 2 0 :heuristic heuristic)
    (bt-path-test-run '((a b) (b a)) 1 0 :goal 'a :heuristic heuristic)
    (bt-path-test-run '((a b) (b c) (c a)) 0 1 :snapshot 'a :heuristic heuristic)
    (bt-path-test-run '((a b) (a c) (b d) (c d) (d g)) 2 0 :snapshot 'a :heuristic heuristic))
  (bt-path-test-run '((a b) (a c) (b g) (c g)) 1 0 :solution-type 'first)
  (bt-path-test-run '((a b)) 0 0 :failure :constraint)
  (bt-path-test-run '((a b)) 0 0 :failure :score)
  (bt-path-test-run '((a a)) 0 0 :failure :verify)
  (format t "~&BACKTRACKING-PATH-SEARCH-CHECKS-PASSED~%"))

(defun test-bt-path-collision ()
  (let* ((root (make-hash-table)) (parent (make-hash-table)) (candidate (make-hash-table))
         (*backtrack-state* (copy-problem-state *start-state*)))
    (setf (gethash 1 root) 'a (gethash 1 parent) 'b (gethash 1 candidate) 'a
          (problem-state.idb *backtrack-state*) candidate)
    (let* ((recent (make-choice :forward-update candidate :inverse-update parent))
           (older (make-choice :forward-update parent :inverse-update root))
           (*choice-stack* (list recent older))
           (*bt-path-fingerprints* '((42 . 1) (42 . 1))))
      (assert (bt-on-current-path-p '(42 . 1))) ; nearest collision, older true repeat
      (let ((*bt-path-fingerprints* '((42 . 1))) (*choice-stack* (list recent)))
        (assert (not (bt-on-current-path-p '(42 . 1)))))
      (assert (eq 'b (gethash 1 parent)))
      (assert (equalp root candidate))))
  (format t "~&BACKTRACKING-PATH-COLLISION-CHECKS-PASSED~%"))

(defun test-bt-path-scratch-trail ()
  (let* ((db (make-hash-table)) (*bt-undo-frame* nil)
         (*idb-hash-acc* nil) (*fixed-idb-hash-acc* nil) (*symmetry-idb-acc* nil))
    (setf (gethash 1 db) nil)
    (let ((before (copy-idb db)) (frame (begin-bt-undo db)))
      (let ((*bt-undo-frame* frame))
        (fold-store 1 'a db t) (fold-store 1 'b db t)
        (fold-remove 1 db t) (fold-store 2 'c db t))
      (let* ((head (bt-undo-frame.head frame)) (live (copy-idb db))
             (choice (make-choice :undo-frame frame))
             (scratch (bt-scratch-parent (copy-idb db) choice)))
        (assert (equalp scratch before))
        (assert (nth-value 1 (gethash 1 scratch)))
        (assert (not (nth-value 1 (gethash 2 scratch))))
        (assert (eq head (bt-undo-frame.head frame)))
        (assert (equalp live db)))
      (restore-bt-undo frame)
      (assert (equalp before db)))
    (let* ((frame (begin-bt-undo db))
           (choice (make-choice :undo-frame frame)))
      (assert (equalp db (bt-scratch-parent (copy-idb db) choice)))
      (assert (null (bt-undo-frame.head frame)))))
  (format t "~&BACKTRACKING-PATH-SCRATCH-CHECKS-PASSED~%"))

(defun bt-path-test-static-error (state)
  (update-bt (problem-state.idb state) '(not (ready)))
  (update-bt *static-db* '(done)))

(defun test-bt-path-static-rejection ()
  (let* ((*bt-path-search-active* t) (*backtrack-state* (copy-problem-state *start-state*))
         (before (bt-update-test-signature *backtrack-state*))
         (static-before (copy-idb *static-db*)) (caught nil))
    (handler-case
        (generate-choices-for-single-combination-bt
          (make-action :name 'static-path-test :eff-defun-name 'bt-path-test-static-error) nil t 0)
      (error (e) (assert (search "static database writes" (princ-to-string e))) (setf caught t)))
    (assert caught)
    (assert (equalp before (bt-update-test-signature *backtrack-state*)))
    (assert (equalp static-before *static-db*))
    ;; Snapshot-style code can write outside an active undo frame: still reject it.
    (let ((*bt-undo-frame* nil) (caught nil))
      (handler-case (fold-remove 'absent *static-db* nil)
        (error (e) (assert (search "static database writes" (princ-to-string e))) (setf caught t)))
      (assert caught)
      (assert (equalp static-before *static-db*)))))

(defun test-bt-path-mode-errors ()
  (let ((*bt-cycle-check* 'path) (*algorithm* 'backtracking) (*problem-type* 'planning)
        (*tree-or-graph* 'tree) (*threads* 0))
    (validate-bt-path-mode)
    (dolist (setting '((*algorithm* . depth-first) (*problem-type* . csp)
                       (*tree-or-graph* . graph) (*threads* . 1) (*solution-validators* . (test))
                       (*search-prefix-validators* . (test)) (*goal-chain-candidate-rejector* . test)
                       (*goal-chain-session* . test) (*goal-chaining-policy* . test)
                       (*final-goal* . test) (*happening-names* . (test))
                       (*auto-wait* . t) (*recorder-prefix-pruning* . t)))
      (let ((old (symbol-value (car setting))) (caught nil))
        (unwind-protect
            (progn (set (car setting) (cdr setting))
                   (handler-case (validate-bt-path-mode)
                     (error (e) (assert (search (symbol-name (car setting)) (princ-to-string e)))
                                (setf caught t)))
                   (assert caught))
          (set (car setting) old))))
    (let ((saved *spliced-tech-names*) (caught nil))
      (unwind-protect
          (progn (setf *spliced-tech-names* '("recorder"))
                 (handler-case (validate-bt-path-mode)
                   (error (e) (assert (search "recorder history" (princ-to-string e))) (setf caught t)))
                 (assert caught))
        (setf *spliced-tech-names* saved))))
  (format t "~&BACKTRACKING-PATH-MODE-CHECKS-PASSED~%"))

(defun test-bt-path-parameters ()
  (assert (eq *bt-cycle-check* 'immediate))
  (assert (eq 'immediate (car (last (normalize-persisted-problem-parameters
                                    (butlast *default-parameters*))))))
  (let ((caught nil))
    (handler-case (check-problem-parameter '*bt-cycle-check* 'invalid)
      (error () (setf caught t)))
    (assert caught))
  (ww-set *bt-cycle-check* path)
  (refresh)
  (assert (eq *bt-cycle-check* 'path))
  (read-globals)
  (assert (eq *bt-cycle-check* 'path))
  (stage backtracking-heuristic)
  (assert (eq *bt-cycle-check* 'immediate))
  (format t "~&BACKTRACKING-PATH-PARAMETER-CHECKS-PASSED~%"))

(defun test-backtracking-path ()
  (test-bt-path-mode-errors)
  (test-bt-path-collision)
  (test-bt-path-scratch-trail)
  (test-bt-path-static-rejection)
  (test-bt-path-search)
  (format t "~&BACKTRACKING-PATH-CHECKS-PASSED~%"))

(defun test-bt-cycle-data-switching ()
  "The same compiled effect must follow runtime mode changes."
  (let* ((action (find 'later-choice *actions* :key #'action.name))
         (effect (symbol-function (action.eff-defun-name action)))
         (original (symbol-function 'update-set-signature))
         (old-mode *bt-cycle-check*) (calls 0))
    (unwind-protect
        (progn
          (setf (symbol-function 'update-set-signature)
                (lambda (ops) (incf calls) (funcall original ops)))
          (dolist (mode '(immediate path immediate))
            (eval `(ww-set *bt-cycle-check* ,mode))
            (setf calls 0)
            (assert (eq effect (symbol-function (action.eff-defun-name action))))
            (let* ((*backtrack-state* (copy-problem-state *start-state*))
                   (before (bt-update-test-signature *backtrack-state*))
                   (choice (first (generate-choices-for-single-combination-bt action nil t 0))))
              (unwind-protect
                  (progn
                    (assert (choice.forward-update choice))
                    (assert (choice.undo-frame choice))
                    (if (eq mode 'path)
                        (progn (assert (zerop calls))
                               (assert (null (choice.inverse-update choice)))
                               (assert (null (choice.forward-sig choice)))
                               (assert (null (choice.inverse-sig choice))))
                        (progn (assert (= calls 2))
                               (assert (choice.inverse-update choice))
                               (assert (choice.forward-sig choice))
                               (assert (choice.inverse-sig choice)))))
                (restore-choice-database-bt choice))
              (assert (equalp before (bt-update-test-signature *backtrack-state*))))))
      (setf (symbol-function 'update-set-signature) original)
      (eval `(ww-set *bt-cycle-check* ,old-mode)))))

(defun test-bt-update-inverse-contract (literal old-literal)
  "Check standalone inverses and trailed omission against the same mutation."
  (dolist (mode '(immediate path))
    (dolist (trailed '(nil t))
      (let* ((*bt-cycle-check* mode) (*problem-type* 'planning)
             (db (make-hash-table)) (*bt-undo-frame* nil))
        (when old-literal (update db old-literal))
        (let* ((before (copy-idb db))
               (frame (when trailed (begin-bt-undo db)))
               (*bt-undo-frame* frame))
          (unwind-protect
              (multiple-value-bind (forward inverse) (update-bt db literal)
                (assert (equal literal forward))
                (if (and trailed (eq mode 'path))
                    (assert (null inverse))
                    (assert (equal inverse
                                   (if (eq (first literal) 'not) (second literal)
                                       (or old-literal (list 'not literal)))))))
            (when frame (restore-bt-undo frame)))
          (when frame (assert (equalp before db))))))))

(defun test-bt-path-cycle-data ()
  (test-bt-cycle-data-switching)
  (test-bt-update-inverse-contract '(done) nil)
  (test-bt-update-inverse-contract '(not (ready)) '(ready))
  (let ((saved *fluent-relation-indices*))
    (unwind-protect
        (progn
          (setf *fluent-relation-indices* (copy-idb saved)
                (gethash 'ready *fluent-relation-indices*) '(1))
          (test-bt-update-inverse-contract '(ready 2) '(ready 1))
          (test-bt-update-inverse-contract '(ready 2) nil))
      (setf *fluent-relation-indices* saved)))
  (let ((*bt-cycle-check* 'path))
    (test-backtracking-snapshot-generation nil)
    (test-backtracking-snapshot-generation t)
    (test-bt-effect-error-restoration)
    (test-bt-constraint-error-restoration)
    (test-bt-reapplication-error-restoration)
    (test-bt-overlapping-siblings))
  (format t "~&BACKTRACKING-PATH-CYCLE-DATA-CHECKS-PASSED~%"))

(defun test-backtracking-updates ()
  (test-bt-set-signatures)
  (test-bt-signature-cycle-check)
  (test-backtracking-incremental-generation)
  (test-backtracking-snapshot-generation nil)
  (test-backtracking-snapshot-generation t)
  (test-bt-entry-restoration)
  (test-bt-expanded-restoration)
  (test-bt-effect-error-restoration)
  (test-bt-constraint-error-restoration)
  (test-bt-reapplication-error-restoration)
  (test-bt-overlapping-siblings)
  (test-bt-path-cycle-data)
  (format t "~&BACKTRACKING-UPDATE-CHECKS-PASSED~%"))
