;;; rumin-topo -- accepted actions from the original start.
(in-package :ww)

(defparameter *accepted-actions*
  '(;; SG1 first gate1 opening: ghost holds tray1* at location2, connector1 on it
    (start-recorder > agent1 starts the recorder)
    (move > agent1* moves via ((walk location3 nil location2)))
    (pickup-tray > agent1* picks up tray1* at location2 from location2)
    (move > agent1 moves via ((walk location3 nil location2)
                              (stairs location2 (staircase1) location4)
                              (walk location4 nil location13)))
    (pickup-connector > agent1 picks up connector1 at location13)
    (move > agent1 moves via ((walk location13 nil location4)))
    (connect-connector > agent1 connects connector1 on tray1* to (connector1* transmitter1) at location2)
    ;; SG2 carry live tray1 through gate1 to location1
    (move > agent1 moves via ((stairs location4 (staircase1) location2)))
    (pickup-tray > agent1 picks up tray1 at location2 from location2)
    (move > agent1 moves via ((stairs location2 (staircase1) location4)
                              (walk location4 nil location13)
                              (stairs location13 (staircase2) location17)
                              (walk location17 (gate1) location1)))
    ;; SG3 revised: preserve loaded ghost tray while interrupting blue
    ;; Previously validated action 11: (put-tray > agent1* puts tray1* on ground at location2)
    (move > agent1* moves via ((stairs location2 (staircase1) location4)
                               (walk location4 nil location13)
                               (stairs location13 (staircase2) location17)))
    (move > agent1 moves via ((walk location1 (gate2) location6)))
    (put-tray > agent1 puts tray1 on plate1 at location6)
    (move > agent1 moves via ((walk location6 (gate3) location7)))
    (pickup-box > agent1 picks up box1 at location7 from location7)
    (move > agent1 moves via ((walk location7 (gate3) location6)
                              (walk location6 (gate2) location1)))
    ;; SG4 under revised SG3: retrieve connector2
    (move > agent1 moves via ((walk location1 nil location11)
                              (walk location11 nil location8)))
    (put-box > agent1 puts box1 on ground at location8)
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 nil location1)
                              (walk location1 (gate2) location6)))
    (pickup-tray > agent1 picks up tray1 at location6 from location6)
    (move > agent1 moves via ((walk location6 (gate2) location1)
                              (walk location1 nil location11)
                              (walk location11 nil location8)))
    (move > agent1 moves via ((jump (location8 ground) nil (location8 box1))))
    (move > agent1 moves via ((jump (location8 box1) (edge4) (location9 ground))))
    (put-tray > agent1 puts tray1 on plate2 at location9)
    (move > agent1 moves via ((stairs location9 (gate4 staircase3) location10)))
    (pickup-connector > agent1 picks up connector2 at location10)
    (move > agent1 moves via ((stairs location10 (gate4 staircase3) location9)
                              (jump location9 (edge4) location8)))
    ;; Accepted recovery check: restore blue using the still-loaded ghost tray
    (move > agent1* moves via ((stairs location17 (staircase2) location13)
                               (walk location13 nil location4)
                               (stairs location4 (staircase1) location2)))
    ;; SG5: live-only blue chain, connector1 on box1 -> connector2
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 nil location1)
                              (walk location1 (gate1) location17)))
    (connect-connector > agent1 connects connector2 on ground to (connector1 receiver1) at location17)
    (move > agent1 moves via ((walk location17 (gate1) location1)
                              (walk location1 nil location11)
                              (walk location11 nil location8)))
    (pickup-box > agent1 picks up box1 at location8 from location8)
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 nil location1)
                              (walk location1 (gate1) location17)
                              (stairs location17 (staircase2) location13)
                              (walk location13 nil location4)
                              (stairs location4 (staircase1) location2)))
    (put-box > agent1 puts box1 on ground at location2)
    (move > agent1 moves via ((stairs location2 (staircase1) location4)))
    (pickup-connector > agent1 picks up connector1 at location4)
    (connect-connector > agent1 connects connector1 on box1 to (connector2 transmitter1) at location2)
    ;; SG6: close cycle 1 with live blue and plate2 preserved
    (put-tray > agent1* puts tray1* on ground at location2)
    (move > agent1* moves via ((walk location2 nil location3)))
    (stop-recorder > agent1* stops the recorder)
    ;; SG7: cycle 2 copied blue holds gate1 while live box moves to location8
    (move > agent1 moves via ((stairs location4 (staircase1) location2)
                              (walk location2 nil location3)))
    (start-recorder > agent1 starts the recorder)
    (move > agent1 moves via ((walk location3 nil location2)
                              (stairs location2 (staircase1) location4)))
    (pickup-connector > agent1 picks up connector1 at location4)
    (put-connector > agent1 puts connector1 on ground without pairings at location4)
    (move > agent1 moves via ((stairs location4 (staircase1) location2)))
    (pickup-box > agent1 picks up box1 at location2 from location2)
    (move > agent1 moves via ((stairs location2 (staircase1) location4)
                              (walk location4 nil location13)
                              (stairs location13 (staircase2) location17)
                              (walk location17 (gate1) location1)
                              (walk location1 nil location11)
                              (walk location11 nil location8)))
    (put-box > agent1 puts box1 on ground at location8)
    ;; SG8: live tray to plate3; ghost tray retains plate2
    (move > agent1 moves via ((jump (location8 ground) nil (location8 box1))))
    (move > agent1 moves via ((jump (location8 box1) (edge4) (location9 ground))))
    (pickup-tray > agent1 picks up tray1 at location9 from location9)
    (move > agent1 moves via ((jump location9 (edge4) location8)
                              (walk location8 nil location11)
                              (walk location11 nil location12)))
    (put-tray > agent1 puts tray1 on plate3 at location12)
    ;; SG9: restore live blue and close cycle 2; tray1 remains on plate3
    (move > agent1 moves via ((walk location12 nil location11)
                              (walk location11 nil location8)))
    (pickup-box > agent1 picks up box1 at location8 from location8)
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 nil location1)
                              (walk location1 (gate1) location17)
                              (stairs location17 (staircase2) location13)
                              (walk location13 nil location4)
                              (stairs location4 (staircase1) location2)))
    (put-box > agent1 puts box1 on ground at location2)
    (move > agent1 moves via ((stairs location2 (staircase1) location4)))
    (pickup-connector > agent1 picks up connector1 at location4)
    (connect-connector > agent1 connects connector1 on box1 to (connector2 transmitter1) at location2)
    (stop-recorder > agent1* stops the recorder)
    ;; SG10: cycle 3 copied blue and plate3 keeper; live box at location8
    (move > agent1 moves via ((stairs location4 (staircase1) location2)
                              (walk location2 nil location3)))
    (start-recorder > agent1 starts the recorder)
    (move > agent1 moves via ((walk location3 nil location2)
                              (stairs location2 (staircase1) location4)))
    (pickup-connector > agent1 picks up connector1 at location4)
    (put-connector > agent1 puts connector1 on ground without pairings at location4)
    (move > agent1 moves via ((stairs location4 (staircase1) location2)))
    (pickup-box > agent1 picks up box1 at location2 from location2)
    (move > agent1 moves via ((stairs location2 (staircase1) location4)
                              (walk location4 nil location13)
                              (stairs location13 (staircase2) location17)
                              (walk location17 (gate1) location1)
                              (walk location1 nil location11)
                              (walk location11 nil location8)))
    (put-box > agent1 puts box1 on ground at location8)
    ;; SG11: live relay at location11 and self-kept relay on plate2
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 nil location1)
                              (walk location1 (gate1) location17)))
    (pickup-connector > agent1 picks up connector2 at location17)
    (move > agent1 moves via ((walk location17 (gate1) location1)
                              (walk location1 nil location11)))
    (connect-connector > agent1 connects connector2 on ground to (receiver2) at location11)
    (move > agent1 moves via ((walk location11 nil location1)
                              (walk location1 (gate1) location17)
                              (stairs location17 (staircase2) location13)
                              (walk location13 nil location4)))
    (pickup-connector > agent1 picks up connector1 at location4)
    (move > agent1 moves via ((walk location4 nil location13)
                              (stairs location13 (staircase2) location17)
                              (walk location17 (gate1) location1)
                              (walk location1 nil location11)
                              (walk location11 nil location8)))
    (move > agent1 moves via ((jump (location8 ground) nil (location8 box1))))
    (move > agent1 moves via ((jump (location8 box1) (edge4) (location9 ground))))
    (connect-connector > agent1 connects connector1 on plate2 to (connector1* connector2) at location9)
    ;; SG12: ghost source turns red; restore the cleared live bridge
    (move > agent1* moves via ((walk location3 nil location2)))
    (pickup-connector > agent1* picks up connector1* at location2)
    (connect-connector > agent1* connects connector1* on box1* to (transmitter2) at location2)
    (pickup-connector > agent1 picks up connector1 at location9)
    (connect-connector > agent1 connects connector1 on plate2 to (connector1* connector2) at location9)
    ;; SG13: box at ladder foot; live tray placed above ladder
    (move > agent1 moves via ((jump location9 (edge4) location8)))
    (pickup-box > agent1 picks up box1 at location8 from location8)
    (move > agent1 moves via ((walk location8 nil location11)
                              (walk location11 (gate5) location14)))
    (put-box > agent1 puts box1 on ground at location14)
    (move > agent1 moves via ((walk location14 (gate5) location11)
                              (walk location11 nil location12)))
    (pickup-tray > agent1 picks up tray1 at location12 from location12)
    (move > agent1 moves via ((walk location12 nil location11)
                              (walk location11 (gate5) location14)))
    (move > agent1 moves via ((jump (location14 ground) nil (location14 box1))))
    (put-tray > agent1 puts tray1 on ground at location5)
    ;; SG14: empty-handed ascent, plate4 keeper, final goal crossing
    (move > agent1 moves via ((jump (location14 box1) nil (location14 ground))))
    (move > agent1 moves via ((ladder location14 (ladder2) location5)))
    (pickup-tray > agent1 picks up tray1 at location5 from location5)
    (move > agent1 moves via ((walk location5 nil location15)))
    (put-tray > agent1 puts tray1 on plate4 at location15)
    (move > agent1 moves via ((walk location15 (gate6) location16)))))

(loop for form in *accepted-actions*
      for index from 1
      for action = (find (first form) *actions* :key #'action.name)
      do (unless action
           (error "Action ~D is unknown: ~S" index form))
         (unless (= (length (strip-display-connectives action (rest form)))
                    (length (action.effect-variables action)))
           (error "Action ~D is malformed: ~S" index form)))

(defparameter *accepted-validation*
  (validate-action-sequence *start-state* *accepted-actions*
                            :goal-test (symbol-function 'goal-fn) :verbose t))

(format t "~%~D actions: success=~S goal-checked=~S goal-satisfied=~S failure-index=~S reason=~S~%"
        (length *accepted-actions*)
        (action-sequence-validation-success-p *accepted-validation*)
        (action-sequence-validation-goal-checked-p *accepted-validation*)
        (action-sequence-validation-goal-satisfied-p *accepted-validation*)
        (action-sequence-validation-failure-index *accepted-validation*)
        (action-sequence-validation-failure-reason *accepted-validation*))
(display-validation-state (action-sequence-validation-final-state *accepted-validation*))

;; Check the newest completed recording independently when this prefix ends at STOP.
;; This also supports intermediate prefixes that have not reached the final goal.
(when (and (action-sequence-validation-success-p *accepted-validation*)
           (eq (first (car (last *accepted-actions*))) 'stop-recorder))
  (let ((path (loop for form in *accepted-actions*
                    for index from 1
                    for action = (find (first form) *actions* :key #'action.name)
                    collect (list index
                                  (cons (first form)
                                        (strip-display-connectives action (rest form)))))))
    (multiple-value-bind (valid-p diagnostic)
        (validate-recorder-cycle-boundary-prefix
          *start-state* path (action-sequence-validation-final-state *accepted-validation*))
      (format t "~%Completed recorder cycle: valid=~S diagnostic=~S~%"
              valid-p diagnostic))))

(defparameter *accepted-validators-p*
  (and (action-sequence-validation-goal-satisfied-p *accepted-validation*)
       (report-solution-validator-verdicts
         *accepted-actions* (action-sequence-validation-final-state *accepted-validation*))))

(when (and (action-sequence-validation-success-p *accepted-validation*)
           (action-sequence-validation-goal-checked-p *accepted-validation*)
           (action-sequence-validation-goal-satisfied-p *accepted-validation*)
           *accepted-validators-p*)
  (with-open-file (*standard-output*
                   (merge-pathnames "doc/problems/rumin-topo/Validation.txt"
                                    (asdf:system-source-directory :wouldwork))
                   :direction :output :if-exists :supersede)
    (format t ";;; rumin-topo -- complete validated solution, ~D actions.~%" (length *accepted-actions*))
    (format t ";;; SUCCESS-P T; GOAL-CHECKED-P T; GOAL-SATISFIED-P T; solution validators accepted~%")
    (format t ";;; To re-validate: (stage rumin-topo), then evaluate this form separately.~%")
    (format t "(validate-solution :verbose")
    (let ((*print-case* :downcase)
          (*print-pretty* nil))
      (loop for form in *accepted-actions*
            for index from 1
            do (format t "~%  ~S" (list index form))))
    (format t ")~2%Final state:~%")
    (display-validation-state (action-sequence-validation-final-state *accepted-validation*))))
