;;; RUMIN-TOPO -- complete solution.  96 actions, four recorder cycles, all closed.
;;; Goal (and (has-location agent1 location16) (ghost-stops-recorder))
;;; -- generic replay, goal, and recorder-cycle validation all succeed.
;;; No object was added, removed, or retyped.
;;;
;;; Objective: reduce the longest recorder cycle, with total action count secondary.
;;; Compared with the 91-action solution's cycles of 52 and 36 actions, this solution has:
;;;   cycle 1:  1-25  (25 actions)
;;;   ordinary: 26-28
;;;   cycle 2: 29-51  (23 actions)
;;;   ordinary: 52-54
;;;   cycle 3: 55-61   (7 actions)
;;;   cycle 4: 62-91  (30 actions)
;;;   ordinary: 92-96
;;; Thus the maximum closed-cycle length falls from 52 to 30 actions, at a cost of five
;;; total actions.  Every cycle ends with an explicit ghost STOP-RECORDER; SOLVE-SUBGOAL
;;; does not close an open recorder cycle automatically.
;;;
;;; The solution depends on recorder-layer-aware connector occupancy: a lit connector
;;; blocks another placement on the same recorder layer, but not at the corresponding
;;; physical location on the other layer.  Mobile live and ghost objects otherwise retain
;;; their recorder isolation.
;;;
;;; Setup:
;;;   (ql:quickload :wouldwork)
;;;   (in-package :ww)
;;;   (stage rumin-topo)

(validate-solution
  (START-RECORDER AGENT1)
  (MOVE AGENT1 ((WALK LOCATION3 NIL LOCATION2) (STAIRS LOCATION2 NIL LOCATION4)
                (WALK LOCATION4 NIL LOCATION13)))
  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION13)
  (MOVE AGENT1 ((WALK LOCATION13 NIL LOCATION4)))
  (MOVE AGENT1* ((WALK LOCATION3 NIL LOCATION2)))
  (PICKUP-TRAY AGENT1* TRAY1* LOCATION2 LOCATION2)
  (CONNECT-CONNECTOR AGENT1 CONNECTOR1 LOCATION2 TRAY1* (CONNECTOR1* TRANSMITTER1))
  (MOVE AGENT1 ((STAIRS LOCATION4 NIL LOCATION2)))
  (PICKUP-TRAY AGENT1 TRAY1 LOCATION2 LOCATION2)
  (MOVE AGENT1 ((WALK LOCATION2 (GATE1) LOCATION1)))
  (MOVE AGENT1* ((STAIRS LOCATION2 NIL LOCATION4)))
  (MOVE AGENT1 ((WALK LOCATION1 (GATE2) LOCATION6)))
  (PUT-TRAY AGENT1 TRAY1 PLATE1 LOCATION6)
  (MOVE AGENT1 ((WALK LOCATION6 (GATE3) LOCATION7)))
  (PICKUP-BOX AGENT1 BOX1 LOCATION7 LOCATION7)
  (MOVE AGENT1 ((WALK LOCATION7 (GATE2 GATE3) LOCATION8)))
  (PUT-BOX AGENT1 BOX1 GROUND LOCATION8)
  (MOVE AGENT1 ((WALK LOCATION8 (GATE2) LOCATION6)))
  (PICKUP-TRAY AGENT1 TRAY1 LOCATION6 LOCATION6)
  (MOVE AGENT1 ((WALK LOCATION6 (GATE2) LOCATION1)))
  (MOVE AGENT1* ((STAIRS LOCATION4 NIL LOCATION2)))
  (MOVE AGENT1 ((WALK LOCATION1 (GATE1) LOCATION3)))
  (MOVE AGENT1* ((WALK LOCATION2 NIL LOCATION3)))
  (PUT-TRAY AGENT1* TRAY1* GROUND LOCATION3)
  (STOP-RECORDER AGENT1*)

  (MOVE AGENT1 ((WALK LOCATION3 NIL LOCATION2)))
  (PUT-TRAY AGENT1 TRAY1 GROUND LOCATION2)
  (MOVE AGENT1 ((WALK LOCATION2 NIL LOCATION3)))

  (START-RECORDER AGENT1)
  (PICKUP-CONNECTOR AGENT1* CONNECTOR1* LOCATION3)
  (MOVE AGENT1* ((WALK LOCATION3 NIL LOCATION2) (STAIRS LOCATION2 NIL LOCATION4)
                 (WALK LOCATION4 NIL LOCATION13)))
  (CONNECT-CONNECTOR AGENT1* CONNECTOR1* LOCATION13 GROUND (RECEIVER1))
  (MOVE AGENT1* ((WALK LOCATION13 NIL LOCATION4) (STAIRS LOCATION4 NIL LOCATION2)))
  (PICKUP-TRAY AGENT1* TRAY1* LOCATION2 LOCATION2)
  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION3)
  (MOVE AGENT1 ((WALK LOCATION3 NIL LOCATION2) (STAIRS LOCATION2 NIL LOCATION4)))
  (CONNECT-CONNECTOR AGENT1 CONNECTOR1 LOCATION2 TRAY1* (CONNECTOR1* TRANSMITTER1))
  (MOVE AGENT1 ((STAIRS LOCATION4 NIL LOCATION2) (WALK LOCATION2 (GATE1) LOCATION8)))
  (MOVE AGENT1 ((JUMP (LOCATION8 GROUND) NIL (LOCATION8 BOX1))))
  (MOVE AGENT1 ((JUMP (LOCATION8 BOX1) NIL (LOCATION9 GROUND))))
  (MOVE AGENT1 ((STAIRS LOCATION9 NIL LOCATION10)))
  (PICKUP-CONNECTOR AGENT1 CONNECTOR2 LOCATION10)
  (MOVE AGENT1 ((STAIRS LOCATION10 NIL LOCATION9) (JUMP LOCATION9 NIL LOCATION8)
                (WALK LOCATION8 (GATE1) LOCATION17)))
  (CONNECT-CONNECTOR AGENT1 CONNECTOR2 LOCATION17 GROUND (RECEIVER1))
  (MOVE AGENT1 ((WALK LOCATION17 (GATE1) LOCATION8)))
  (PICKUP-BOX AGENT1 BOX1 LOCATION8 LOCATION8)
  (MOVE AGENT1 ((WALK LOCATION8 (GATE1) LOCATION2)))
  (PUT-BOX AGENT1 BOX1 GROUND LOCATION2)
  (PUT-TRAY AGENT1* TRAY1* GROUND LOCATION2)
  (MOVE AGENT1* ((WALK LOCATION2 NIL LOCATION3)))
  (STOP-RECORDER AGENT1*)

  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION2)
  (CONNECT-CONNECTOR AGENT1 CONNECTOR1 LOCATION2 BOX1 (CONNECTOR2 TRANSMITTER1))
  (MOVE AGENT1 ((WALK LOCATION2 NIL LOCATION3)))

  (START-RECORDER AGENT1)
  (MOVE AGENT1 ((WALK LOCATION3 NIL LOCATION2)))
  (PICKUP-TRAY AGENT1 TRAY1 LOCATION2 LOCATION2)
  (MOVE AGENT1 ((WALK LOCATION2 (GATE1) LOCATION12)))
  (PUT-TRAY AGENT1 TRAY1 PLATE3 LOCATION12)
  (MOVE AGENT1 ((WALK LOCATION12 (GATE1) LOCATION3)))
  (STOP-RECORDER AGENT1*)

  (START-RECORDER AGENT1)
  (MOVE AGENT1 ((WALK LOCATION3 NIL LOCATION2)))
  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION2)
  (MOVE AGENT1 ((WALK LOCATION2 (GATE1) LOCATION8)))
  (PUT-CONNECTOR AGENT1 CONNECTOR1 LOCATION8 GROUND)
  (MOVE AGENT1 ((WALK LOCATION8 (GATE1) LOCATION2)))
  (PICKUP-BOX AGENT1 BOX1 LOCATION2 LOCATION2)
  (MOVE AGENT1 ((WALK LOCATION2 (GATE1) LOCATION8)))
  (PUT-BOX AGENT1 BOX1 GROUND LOCATION8)
  (PICKUP-CONNECTOR AGENT1 CONNECTOR1 LOCATION8)
  (MOVE AGENT1 ((JUMP (LOCATION8 GROUND) NIL (LOCATION8 BOX1))))
  (MOVE AGENT1 ((JUMP (LOCATION8 BOX1) NIL (LOCATION9 GROUND))))
  (CONNECT-CONNECTOR AGENT1 CONNECTOR1 LOCATION9 PLATE2 (CONNECTOR2*))
  (MOVE AGENT1 ((JUMP LOCATION9 NIL LOCATION8) (WALK LOCATION8 (GATE1) LOCATION17)))
  (PICKUP-CONNECTOR AGENT1 CONNECTOR2 LOCATION17)
  (MOVE AGENT1 ((WALK LOCATION17 (GATE1) LOCATION11)))
  (CONNECT-CONNECTOR AGENT1 CONNECTOR2 LOCATION11 GROUND (CONNECTOR1 RECEIVER2))
  (MOVE AGENT1* ((WALK LOCATION3 NIL LOCATION2)))
  (PICKUP-CONNECTOR AGENT1* CONNECTOR1* LOCATION2)
  (CONNECT-CONNECTOR AGENT1* CONNECTOR1* LOCATION2 BOX1* (CONNECTOR2* TRANSMITTER2))
  (MOVE AGENT1 ((WALK LOCATION11 NIL LOCATION8)))
  (PICKUP-BOX AGENT1 BOX1 LOCATION8 LOCATION8)
  (MOVE AGENT1 ((WALK LOCATION8 (GATE5) LOCATION14)))
  (PUT-BOX AGENT1 BOX1 GROUND LOCATION14)
  (MOVE AGENT1 ((WALK LOCATION14 (GATE5) LOCATION12)))
  (PICKUP-TRAY AGENT1 TRAY1 LOCATION12 LOCATION12)
  (MOVE AGENT1 ((WALK LOCATION12 (GATE5) LOCATION14)))
  (PUT-TRAY AGENT1 TRAY1 BOX1 LOCATION14)
  (MOVE AGENT1* ((WALK LOCATION2 NIL LOCATION3)))
  (STOP-RECORDER AGENT1*)

  (MOVE AGENT1 ((LADDER LOCATION14 (LADDER2) LOCATION5)))
  (PICKUP-TRAY AGENT1 TRAY1 LOCATION14 LOCATION5)
  (MOVE AGENT1 ((WALK LOCATION5 NIL LOCATION15)))
  (PUT-TRAY AGENT1 TRAY1 PLATE4 LOCATION15)
  (MOVE AGENT1 ((WALK LOCATION15 (GATE6) LOCATION16)))
)
