;;; Optional supplied-arrangement diagnostic (T34, specification 6.2).
;;; Load after constraint-profile.lisp. Not an ASDF component or include-tech.
;;; Plain Common Lisp, callees first, no problem identities, no actions/search.
(in-package :ww)

(defun arrangement-canonical-fact (fact)
  (cons (or (car (gethash (first fact) *bijective-canonical*)) (first fact))
        (copy-tree (rest fact))))

(defun arrangement-facts (state)
  (sort (remove-duplicates (mapcar #'arrangement-canonical-fact (database state)) :test #'equal)
        #'string< :key #'prin1-to-string))

(defun arrangement-value (relation object facts)
  (third (find-if (lambda (fact) (and (eq relation (first fact)) (eq object (second fact)))) facts)))

(defun arrangement-configuration (facts)
  (remove-if-not (lambda (fact) (member (first fact) '(has-location on holding mounted-on paired))) facts))

(defun arrangement-type-p (value spec)
  (cond ((nth-value 1 (gethash spec *types*)) (member value (census-type-instances spec)))
        ((and (consp spec) (eq (first spec) 'either))
         (some (lambda (part) (arrangement-type-p value part)) (rest spec)))
        ((lisp-type-p spec) (typep value spec))))

(defun arrangement-check-fact-types (facts)
  (dolist (fact facts)
    (multiple-value-bind (signature present) (gethash (first fact) *relations*)
      (when (eq signature t) (setf signature nil))
      (unless (and present (listp signature) (= (length signature) (length (rest fact))))
        (error "Unknown dynamic relation or wrong arity: ~S" fact))
      (loop for value in (rest fact) for spec in signature
            unless (arrangement-type-p value spec)
              do (error "Wrong argument type ~S for ~S in ~S" value spec fact)))))

(defun arrangement-check-bijective-indexes (state)
  (let ((raw (database state)))
    (dolist (fact raw)
      (let* ((canonical (arrangement-canonical-fact fact))
             (indexes (gethash (first canonical) *bijective-relations*)))
        (when indexes
          (dolist (index indexes)
            (unless (member (cons index (rest canonical)) raw :test #'equal)
              (error "Inconsistent bijective indexes for ~S" canonical))))))))

(defun arrangement-check-functional-facts (facts)
  (dolist (relation '(has-location on holding mounted-on))
    (let ((rows (remove-if-not (lambda (fact) (eq (first fact) relation)) facts)))
      (dolist (row rows)
        (when (> (count (second row) rows :key #'second) 1)
          (error "Multiple values for ~S" row))
        (when (and (member relation '(holding mounted-on))
                   (> (count (third row) rows :key #'third) 1))
          (error "Multiple owners of ~S" row))))))

(defun arrangement-check-presence (facts mappings phase)
  (dolist (object (census-type-instances 'mobile-object))
    (let ((ghost (find object mappings :key #'third)))
      (when (and ghost (eq phase :closed)
                 (some (lambda (fact) (member object (alexandria:flatten (rest fact)))) facts))
        (error "Closed recorder retains ghost reference: ~S" object))
      (when (and (not ghost)
                 (not (or (arrangement-value 'has-location object facts)
                          (find object facts :key (lambda (fact) (when (eq (first fact) 'holding) (third fact))))
                          (arrangement-value 'mounted-on object facts))))
        (error "Live mobile object has no physical state: ~S" object)))))

(defun arrangement-check-dependency-cycles (facts)
  "Follow ON and reverse HOLDING together before any recursive engine height query."
  (dolist (object (census-type-instances 'mobile-object))
    (let ((current object) (seen nil))
      (loop while current
            do (when (member current seen)
                 (error "Support/holding cycle from ~S through ~S" object current))
               (push current seen)
               (setf current
                     (or (arrangement-value 'on current facts)
                         (second (find-if (lambda (fact)
                                            (and (eq (first fact) 'holding)
                                                 (eq (third fact) current))) facts))))))))

(defun arrangement-check-support-policy (state facts)
  (dolist (fact facts)
    (case (first fact)
      (on
       (unless (relay-view-call 'support-use-allowed state (second fact) (third fact))
         (error "Support violates recorder policy: ~S" fact))
       (unless (member (third fact)
                       (relay-view-call 'physical-supports-at state
                                        (arrangement-value 'has-location (second fact) facts) t))
         (error "Support is not an available physical surface: ~S" fact)))
      (holding
       (when (relay-view-mappings)
         (unless (relay-view-call 'same-recording-side state (second fact) (third fact))
           (error "Holding crosses recording layers: ~S" fact)))))))

(defun arrangement-check-pairings (state facts mappings)
  (dolist (connector (census-type-instances 'connector))
    (let ((reason (relay-view-pairing-reason state connector mappings)))
      (when reason (error "~S: ~A" connector reason))))
  (dolist (pair facts)
    (when (eq (first pair) 'paired)
      (dolist (object (rest pair))
        (when (and (member object (census-type-instances 'connector))
                   (not (arrangement-value 'has-location object facts)))
          (error "Pairing names a connector without a beam location: ~S" pair))))))

(defun arrangement-validate-state (state phase)
  "Validate before recursive height queries; use runtime policy for shared held trays."
  (let* ((facts (arrangement-facts state))
         (mappings (relay-view-mappings))
         (literals (append facts (mapcar #'arrangement-canonical-fact (list-static-db)))))
    (arrangement-check-fact-types facts)
    (arrangement-check-bijective-indexes state)
    (arrangement-check-functional-facts facts)
    (arrangement-check-dependency-cycles facts)
    (check-init-object-placement-consistency literals)
    (when (find 'mounted-on facts :key #'first)
      (check-init-mounted-fan-consistency literals))
    (arrangement-check-presence facts mappings phase)
    (arrangement-check-support-policy state facts)
    (arrangement-check-pairings state facts mappings)
    facts))

(defun arrangement-validation-reason (state phase)
  (handler-case (progn (arrangement-validate-state state phase) nil)
    (error (condition) (princ-to-string condition))))

(defun arrangement-input-reason (scenario)
  (or (relay-view-input-reason scenario)
      (cond ((not (member (getf scenario :view) '(:physical :recording))) "receiver view missing")
            ((not (member (getf scenario :receiver) (census-type-instances 'receiver))) "receiver missing or unknown")
            ((null (getf scenario :chains)) "at least one supplied identity chain is required")
            ((some (lambda (chain) (not (eq (car (last chain)) (getf scenario :receiver))))
                   (getf scenario :chains)) "chain ends at a different receiver")
            ((getf scenario :gate-premises) "forced gate premises forbidden; supply primitive controls")
            ((and (eq (getf scenario :view) :recording)
                  (not (member 'update-recording-receiver-status! *update-names*)))
             "recording receiver consequence machinery unavailable")
            ((not (member 'propagate-changes! *update-names*)) "propagation unavailable")
            ((not (member "-support-motion" *spliced-tech-names* :test #'string=)) "physical support validation unavailable")
            ((problem-state.happenings (getf scenario :state)) "scheduled happenings not supported by this immediate check"))
      (relay-view-context-reason scenario (getf scenario :view) (relay-view-mappings))))

(defun arrangement-state-snapshot (state)
  (list (arrangement-facts state) (copy-tree (list-database (problem-state.hidb state)))
        (copy-tree (problem-state.happenings state)) (problem-state.time state)
        (problem-state.value state) (problem-state.heuristic state)
        (problem-state.name state) (copy-tree (problem-state.instantiations state))))

(defun arrangement-propagate (state)
  "Only the existing bounded engine fixpoint, with ordinary transition edge semantics."
  (let ((*applying-init-action* nil))
    (and (relay-view-call 'propagate-changes! state) (not (state-is-inconsistent state)))))

(defun arrangement-difference (before after)
  (list :removed (set-difference before after :test #'equal)
        :added (set-difference after before :test #'equal)))

(defun arrangement-evaluate-settled (scenario state before)
  (let* ((after (arrangement-facts state))
         (second-state (%copy-problem-state state t))
         (snapshot (arrangement-state-snapshot state)))
    (unless (and (arrangement-propagate second-state)
                 (equal snapshot (arrangement-state-snapshot second-state)))
      (return-from arrangement-evaluate-settled
        (list :status :unresolved :reason "second propagation pass is not a fixed point"
              :settled-state state :idempotent nil)))
    (let* ((settled-scenario (copy-list scenario))
           (configuration (arrangement-difference (arrangement-configuration before)
                                                   (arrangement-configuration after))))
      (setf (getf settled-scenario :state) state)
      (let* ((views (relay-view-results settled-scenario))
             (view (getf scenario :view))
             (selected (find view views :key (lambda (row) (getf row :view))))
             (active (member (list (if (eq view :physical) 'active 'recording-active)
                                   (getf scenario :receiver)) after :test #'equal))
             (intact (not (or (getf configuration :removed) (getf configuration :added))))
             (working (and active (eq :clear (getf selected :status)))))
        (list :status (cond ((eq :unresolved (getf selected :status)) :unresolved)
                            ((eq :invalid (getf selected :status)) :inconsistent)
                            ((and intact working) :stable-and-beam-working)
                            (t :settled-but-failed))
              :reason (cond ((member (getf selected :status) '(:unresolved :invalid))
                             (getf selected :reason))
                            ((not intact) "requested physical configuration changed")
                            ((not working) "configuration stationary but required beam failed")
                            (t "configuration intact and beam working at engine fixed point"))
              :settled-state state :idempotent t :receiver-active (not (null active))
              :configuration-changes configuration :changes (arrangement-difference before after)
              :views views)))))

(defun arrangement-run (scenario state)
  (let ((before (arrangement-facts state)))
    (unless (arrangement-propagate state)
      (return-from arrangement-run
        (list :status :inconsistent
              :reason "engine rejected state or reached propagation bound; no impossibility claim"
              :settled-state state :changes (arrangement-difference before (arrangement-facts state)))))
    (let ((invalid (arrangement-validation-reason state (getf scenario :phase))))
      (if invalid
        (list :status :inconsistent :reason (format nil "invalid propagated configuration: ~A" invalid)
              :settled-state state)
        (arrangement-evaluate-settled scenario state before)))))

(defun arrangement-check-private (scenario)
  (let ((reason (arrangement-input-reason scenario)))
    (when reason (return-from arrangement-check-private (list :status :unresolved :reason reason))))
  (let ((state (%copy-problem-state (getf scenario :state) t)))
    (when (state-is-inconsistent state)
      (return-from arrangement-check-private (list :status :invalid :reason "reference already marked inconsistent")))
    (let ((invalid (arrangement-validation-reason state (getf scenario :phase))))
      (when invalid (return-from arrangement-check-private (list :status :invalid :reason invalid))))
    (dolist (chain (getf scenario :chains))
      (let ((invalid (relay-view-chain-input-reason state chain (relay-view-mappings))))
        (when invalid (return-from arrangement-check-private (list :status :invalid :reason invalid)))))
    (dolist (hop (getf scenario :hops))
      (let ((row (relay-view-hop-result state nil hop)))
        (when (eq (getf row :status) :invalid)
          (return-from arrangement-check-private
            (list :status :invalid :reason (getf row :reason))))))
    (handler-case (arrangement-run scenario state)
      (error (condition)
        (list :status :unresolved :stage :consequence-or-beam-evaluation
              :reason (format nil "engine/evaluation exception: ~A" condition))))))

(defun check-relay-arrangement (scenario)
  "Check one supplied complete arrangement, not how to reach it or keep it through actions."
  (handler-case
      (append (arrangement-check-private scenario)
              (list :view (getf scenario :view) :receiver (getf scenario :receiver)
                    :phase (getf scenario :phase) :provenance (getf scenario :provenance)
                    :input-facts (when (typep (getf scenario :state) 'problem-state)
                                   (arrangement-facts (getf scenario :state)))
                    :scope "one supplied configuration; no reachability or future-transition guarantee"))
    (error (condition) (list :status :unresolved :stage :input-check
                            :reason (format nil "check exception: ~A" condition)))))

(defun report-relay-arrangement (scenario)
  (let* ((*print-pretty* nil) (result (check-relay-arrangement scenario)))
    (format t "~&SUPPLIED ARRANGEMENT (T34) ~A~%  ~A~%" (getf result :status) (getf result :reason))
    (format t "  view ~S; receiver ~S; phase ~S; provenance ~A~%"
            (getf result :view) (getf result :receiver) (getf result :phase) (getf result :provenance))
    (format t "  supplied reference facts ~S~%" (getf result :input-facts))
    (format t "  configuration, primitives and edge memory are supplied premises; geometry/wiring inherited from staged ~A.~%" *problem-name*)
    (format t "  gate/fan/color/receiver caches are rederived; no gate forcing, action or release event.~%")
    (format t "  ~A~%  idempotent ~S; receiver active ~S~%"
            (getf result :scope) (getf result :idempotent) (getf result :receiver-active))
    (dolist (key '(:configuration-changes :changes))
      (format t "  ~A ~S~%" key (getf result key)))
    (when (getf result :settled-state)
      (format t "  settled facts ~S~%" (arrangement-facts (getf result :settled-state))))
    (dolist (view (getf result :views))
      (format t "  T33 ~A ~A: ~A~%" (getf view :view) (getf view :status) (getf view :reason))
      (dolist (row (getf view :chains))
        (format t "    chain ~S ~A: ~A~%" (getf row :input) (getf row :status) (getf row :reason))))
    result))
