;;; Accepted E003 output, replay to restore.
(:problem crelay-topo :checkpoint c004 :parent c003
 :source "E003-output.txt"
 :actions ((1.0 (START-RECORDER AGENT1)) (2.0 (MOVE AGENT1* ((WALK LOCATION1 NIL LOCATION2))))
                         (3.0 (MOVE AGENT1* ((STEP (LOCATION2 GROUND) NIL (LOCATION2 PLATE1)))))
                         (4.0 (MOVE AGENT1 ((WALK LOCATION1 (GATE1 GATE3) LOCATION9))))
                         (5.0 (PICKUP-CONNECTOR-RETAINING-PAIRINGS AGENT1 CONNECTOR1 LOCATION9))
                         (6.0 (MOVE AGENT1 ((WALK LOCATION9 (GATE1 GATE3) LOCATION2))))
                         (7.0 (PUT-CONNECTOR AGENT1 CONNECTOR1 PLATE1 LOCATION2)) (8.0 (MOVE AGENT1 ((WALK LOCATION2 NIL LOCATION1))))
                         (9.0 (CANCEL-PLAYBACK AGENT1)) (10.0 (START-RECORDER AGENT1))
                         (11.0 (MOVE AGENT1* ((WALK LOCATION1 (GATE1) LOCATION7))))
                         (12.0 (MOVE AGENT1 ((WALK LOCATION1 (GATE1) LOCATION4))))
                         (13.0 (MOVE AGENT1 ((STEP (LOCATION4 GROUND) NIL (LOCATION4 BLOWER1))))) (14.0 (TOGGLE-SWITCH AGENT1 SWITCH1))
                         (15.0 (PICKUP-TRAY AGENT1* TRAY1* LOCATION7 LOCATION7))
                         (16.0 (MOVE AGENT1 ((JUMP LOCATION20 NIL LOCATION5) (WALK LOCATION5 (GATE1) LOCATION2))))
                         (17.0 (PICKUP-CONNECTOR-RETAINING-PAIRINGS AGENT1 CONNECTOR1 LOCATION2)))
 :endpoint (:FACTS
               ((BLOWING BLOWER1) (DEPRESSED PLATE1) (DEPRESSED PLATE2) (HAS-LOCATION AGENT1 LOCATION2) (HAS-LOCATION AGENT1* LOCATION7)
                (HAS-LOCATION BOX1 LOCATION6) (HAS-LOCATION BOX1* LOCATION6) (HAS-LOCATION CONNECTOR1* LOCATION2)
                (HAS-LOCATION TRAY1 LOCATION7) (HAS-LOCATION TRAY1* LOCATION7) (HOLDING1 AGENT1 CONNECTOR1) (HOLDING1 AGENT1* TRAY1*)
                (HOLDING2 AGENT1 CONNECTOR1) (HOLDING2 AGENT1* TRAY1*) (ON CONNECTOR1* PLATE1) (ON TRAY1 PLATE2) (OPEN GATE1) (OPEN GATE3)
                (OPEN GATE5) (RECORDER-CYCLES-USED 2) (RECORDING-DEPRESSED PLATE1) (RECORDING-IN-PROGRESS) (RECORDING-OPEN GATE1)
                (RECORDING-OPEN GATE2) (RECORDING-OPEN GATE5) (SWITCHED-ON SWITCH1) (TURNING BLOWER1))
               :HAPPENING-FACTS NIL :HAPPENINGS NIL :TIME 17.0 :VALUE 0.0 :POLICY-CONTEXT (:CYCLE-COUNT 2 :RECORDING-OPEN-P T)))
