(:PROBLEM CRELAY-TOPO :EXPERIMENT E013 :PARENT C008 :ORIGIN
 (:FACTS
  ((DEPRESSED PLATE2) (HAS-LOCATION AGENT1 LOCATION1) (HAS-LOCATION BOX1 LOCATION6) (HAS-LOCATION CONNECTOR1 LOCATION9)
   (HAS-LOCATION TRAY1 LOCATION7) (ON TRAY1 PLATE2) (OPEN GATE2) (OPEN GATE3) (OPEN GATE5) (RECORDING-OPEN GATE2) (RECORDING-OPEN GATE5))
  :HAPPENING-FACTS NIL :HAPPENINGS NIL :TIME 0.0 :VALUE 0.0 :POLICY-CONTEXT (:CYCLE-COUNT 0 :RECORDING-OPEN-P NIL))
 :ORIGINAL-GOAL (HAS-LOCATION AGENT1 LOCATION19) :SETTINGS
 ((*THREADS* 16) (*DEPTH-CUTOFF* 10) (*SOLUTION-TYPE* FIRST) (*ALGORITHM* DEPTH-FIRST) (*TREE-OR-GRAPH* GRAPH) (*RANDOMIZE-SEARCH* NIL)
  (*SYMMETRY-PRUNING* NIL) (*MIN-STEPS-PRUNING-ENABLED* T) (*RECORDER-PREFIX-PRUNING* NIL) (*MAX-RECORDER-CYCLES* 2)
  (*MAX-CONNECTOR-PAIRINGS* 3))
 :PARENT-ACTIONS
 ((1.0 (START-RECORDER AGENT1)) (2.0 (MOVE AGENT1* ((WALK LOCATION1 NIL LOCATION2))))
  (3.0 (MOVE AGENT1* ((STEP (LOCATION2 GROUND) NIL (LOCATION2 PLATE1))))) (4.0 (MOVE AGENT1 ((WALK LOCATION1 (GATE1 GATE3) LOCATION9))))
  (5.0 (PICKUP-CONNECTOR-RETAINING-PAIRINGS AGENT1 CONNECTOR1 LOCATION9)) (6.0 (MOVE AGENT1 ((WALK LOCATION9 (GATE1 GATE3) LOCATION2))))
  (7.0 (PUT-CONNECTOR AGENT1 CONNECTOR1 PLATE1 LOCATION2)) (8.0 (MOVE AGENT1 ((WALK LOCATION2 NIL LOCATION1))))
  (9.0 (CANCEL-PLAYBACK AGENT1)) (10.0 (START-RECORDER AGENT1)) (11.0 (MOVE AGENT1* ((WALK LOCATION1 (GATE1) LOCATION7))))
  (12.0 (MOVE AGENT1 ((WALK LOCATION1 (GATE1) LOCATION4)))) (13.0 (MOVE AGENT1 ((STEP (LOCATION4 GROUND) NIL (LOCATION4 BLOWER1)))))
  (14.0 (TOGGLE-SWITCH AGENT1 SWITCH1)) (15.0 (PICKUP-TRAY AGENT1* TRAY1* LOCATION7 LOCATION7))
  (16.0 (MOVE AGENT1* ((WALK LOCATION7 NIL LOCATION5)))) (17.0 (MOVE AGENT1 ((JUMP (LOCATION20 GROUND) NIL (LOCATION5 TRAY1*)))))
  (18.0 (TOGGLE-SWITCH AGENT1 SWITCH1)) (19.0 (MOVE AGENT1 ((JUMP (LOCATION5 TRAY1*) (GATE2) (LOCATION6 GROUND)))))
  (20.0 (PICKUP-BOX AGENT1 BOX1 LOCATION6 LOCATION6)) (21.0 (MOVE AGENT1 ((JUMP LOCATION6 (GATE2) LOCATION4)))))
 :PARENT-ENDPOINT
 (:FACTS
  ((DEPRESSED PLATE1) (DEPRESSED PLATE2) (HAS-LOCATION AGENT1 LOCATION4) (HAS-LOCATION AGENT1* LOCATION5) (HAS-LOCATION BOX1* LOCATION6)
   (HAS-LOCATION CONNECTOR1 LOCATION2) (HAS-LOCATION CONNECTOR1* LOCATION2) (HAS-LOCATION TRAY1 LOCATION7) (HAS-LOCATION TRAY1* LOCATION5)
   (HOLDING1 AGENT1 BOX1) (HOLDING1 AGENT1* TRAY1*) (HOLDING2 AGENT1 BOX1) (HOLDING2 AGENT1* TRAY1*) (ON CONNECTOR1 PLATE1)
   (ON CONNECTOR1* PLATE1) (ON TRAY1 PLATE2) (OPEN GATE1) (OPEN GATE2) (OPEN GATE3) (OPEN GATE5) (RECORDER-CYCLES-USED 2)
   (RECORDING-DEPRESSED PLATE1) (RECORDING-IN-PROGRESS) (RECORDING-OPEN GATE1) (RECORDING-OPEN GATE2) (RECORDING-OPEN GATE5))
  :HAPPENING-FACTS NIL :HAPPENINGS NIL :TIME 21.0 :VALUE 0.0 :POLICY-CONTEXT (:CYCLE-COUNT 2 :RECORDING-OPEN-P T))
 :GOAL
 (AND (ON BOX1 PLATE1) (ON TRAY1 PLATE2) (HAS-LOCATION CONNECTOR1 LOCATION9) (PAIRED CONNECTOR1 TRANSMITTER1) (PAIRED CONNECTOR1 REPEATER1)
      (HAS-LOCATION AGENT1 LOCATION1) (NOT (SWITCHED-ON SWITCH2)) (NOT (RECORDING-SWITCHED-ON SWITCH2)) (RECORDING-IN-PROGRESS)
      (RECORDER-CYCLES-USED 2))
 :STATUS :REQUEST-SAVED-BEFORE-SEARCH)
