;;; Focused immediate-consequence fixtures. No search required.
(in-package :ww)
(ww-set *problem-name* t34-arrangement)
(ww-set *problem-type* planning)
(ww-set *solution-type* first)
(ww-set *depth-cutoff* 0)
(ww-set *max-connector-pairings* 2)
(define-types
  agent (worker)
  connector (relay)
  box (pedestal rider)
  tray (tray)
  fan (puck)
  wall-gears (mount-drive)
  pressure-plate (control landing)
  toggle-plate (loop-control lift-control)
  wall-blower (sweeper loop-forward loop-back)
  floor-blower (lift)
  gate (shutter)
  transmitter (source)
  receiver (target)
  hue (red)
  location (safe beam-site swept delivered loop-a loop-b floor-site hover-site))
(include-tech plate)
(include-tech box)
(include-tech tray)
(include-tech wall-blower)
(include-tech floor-blower)
(include-tech beam-relay)
(include-tech visibility)
(include-tech gate)
(define-init
  (has-location worker safe)
  (has-location relay beam-site)
  (has-location pedestal swept)
  (has-location rider swept)
  (on rider pedestal)
  (has-location tray safe)
  (mounted-on puck mount-drive)
  (has-position mount-drive safe)
  (aimed-at mount-drive delivered)
  (controls ((lift-control)) mount-drive normal)
  (has-position control delivered)
  (has-position landing delivered)
  (has-position loop-control safe)
  (has-position lift-control safe)
  (has-position sweeper swept)
  (aimed-at sweeper delivered)
  (controls ((loop-control)) sweeper normal)
  (has-position loop-forward loop-a)
  (aimed-at loop-forward loop-b)
  (has-position loop-back loop-b)
  (aimed-at loop-back loop-a)
  (controls ((loop-control)) loop-forward normal)
  (controls ((loop-control)) loop-back normal)
  (has-position lift floor-site)
  (aimed-at lift hover-site)
  (controls ((lift-control)) lift normal)
  (has-elevation hover-site 10)
  (controls ((control)) shutter inverted)
  (paired relay source)
  (paired relay target)
  (has-chroma source red)
  (has-chroma target red)
  (los-via beam-site () source)
  (los-via beam-site (shutter) target))
(define-init-action initialize-derived-state 0 () (always-true) ()
  (assert (propagate-changes!)))
(define-goal (active target))
