(ql:quickload :wouldwork)
(in-package :ww)
(stage crelay-topo)
(load (merge-pathnames "tech/constraint-profile.lisp" (asdf:system-source-directory :wouldwork)))
(let ((output (with-output-to-string (stream)
                (let ((*standard-output* stream))
                  (report-height-and-reach-lattice)))))
  (assert (search "type heights (21 types; 3 authored overrides)" output))
  (assert (search "connector1  1, 2, 5/2" output))
  (assert (search "agent1 0 -> tray1 3/2  NO" output))
  (assert (search "unreachable from ground (placement reach limit 1)" output))
  (assert (= 5 (length (height-lattice-placement-supports *start-state*)))))
(format t "S5 acceptance: 5 assertions passed.~%")