;;; T32 focused acceptance. No search or solution replay.
;;; Load after the diagnostic; pure checks run immediately, staged checks called separately.
(in-package :ww)
(defparameter *t32-checks* 0)
(defun t32-check (label passed)
  (unless passed (error "T32 failed: ~A" label))
  (incf *t32-checks*)
  (format t "~&PASS ~A~%" label))

(defun t32-pure-checks ()
  (t32-check "stream meets inclusive top" (wall-stream-strikes-p 0 1 1))
  (t32-check "body below stream" (not (wall-stream-strikes-p 0 1 2)))
  (t32-check "base at stream is unswept" (not (wall-stream-strikes-p 1 2 1)))
  (t32-check "body above stream" (not (wall-stream-strikes-p 2 3 1)))
  (t32-check "floor lift" (eq 'lift (coupling-motion-role t t nil)))
  (t32-check "wall horizontal transport" (eq 'horizontal-transport (coupling-motion-role t nil t)))
  (t32-check "other aimed drive transport" (eq 'transport (coupling-motion-role t nil nil)))
  (t32-check "no aimed destination no motion role" (null (coupling-motion-role nil t nil))))

(defun t32-wind-state (physical recording)
  "Injected fixture copied from start, not claimed to be a reachable puzzle state."
  (let ((state (copy-problem-state *start-state*)))
    (revise (problem-state.idb state)
            `((has-location connector1 location3)
              (has-location connector1* location3)
              (paired connector1 transmitter1) (paired connector1* transmitter1)
              ,(if physical '(turning blower1) '(not (turning blower1)))
              ,(if recording '(recording-turning blower1) '(not (recording-turning blower1)))))
    state))

(defun t32-fact-p (state fact)
  (member fact (database state) :test #'equal))

(defun t32-sweep-case (physical recording)
  (let ((state (t32-wind-state physical recording)))
    (funcall (symbol-function 'sweep-occupants-away!) state 'blower1)
    (t32-check (format nil "live motion: physical ~A recording ~A" physical recording)
               (t32-fact-p state (list 'has-location 'connector1
                                      (if physical 'location6 'location3))))
    (t32-check (format nil "ghost motion: physical ~A recording ~A" physical recording)
               (t32-fact-p state (list 'has-location 'connector1*
                                      (if recording 'location6 'location3))))
    (t32-check "both pairings survive sweep"
               (and (t32-fact-p state '(paired connector1 transmitter1))
                    (t32-fact-p state '(paired connector1* transmitter1))))))

(defun t32-windtunnel-checks ()
  (let ((before (database *start-state*)))
    (t32-sweep-case t nil)
    (t32-sweep-case nil t)
    (t32-sweep-case t t)
    (t32-sweep-case nil nil)
    (t32-check "start state unchanged" (equal before (database *start-state*))))
  (let* ((controls (control-facts))
         (chains (cdr (first (hint-relay-chains '(receiver1) controls))))
         (chain (first chains))
         (exposure (first (getf chain :wall-exposures)))
         (table (coupling-role-table controls (traversal-arc-facts) nil)))
    (t32-check "one geometric candidate retained" (= 1 (length chains)))
    (t32-check "candidate remains bootstrap, not a stable realization" (eq :bootstrap (getf chain :class)))
    (t32-check "two-connector geometric cost unchanged" (= 2 (getf chain :bodies)))
    (t32-check "ground contact" (and (= 0 (getf exposure :base)) (= 1 (getf exposure :top))
                                      (getf exposure :struck)))
    (t32-check "same-view physical gate conflict" (equal '(gate1) (getf exposure :live-conflict-gates)))
    (let* ((rows (relay-wall-exposures '((location3 2 (hypothetical-support) nil)) '(gate1) controls))
           (row (first rows)))
      (t32-check "raised connector direct contact absent" (not (getf row :struck)))
      (t32-check "raised support stability unresolved" (search "support motion still unresolved" (relay-wall-exposure-text row))))
    (let ((axioms (copy-tree (device-state-axioms controls))))
      (dolist (axiom axioms) (when (eq (first axiom) 'turning) (setf (fifth axiom) :override)))
      (t32-check "live override prevents conflict inference"
                 (null (relay-wall-required-gates 'blower1 '(gate1) controls axioms))))
    (let ((changed (copy-tree controls)))
      (setf (fourth (find 'blower1 changed :key #'third)) 'inverted)
      (t32-check "opposite control polarity prevents conflict inference"
                 (null (relay-wall-required-gates 'blower1 '(gate1) changed (device-state-axioms controls)))))
    (t32-check "CC wall has horizontal role" (member 'horizontal-transport (coupling-roles 'blower1 table)))
    (t32-check "CC wall lacks lift role" (not (member 'lift (coupling-roles 'blower1 table))))
    (t32-check "horizontal role uses transport subsystem" (equal '(transport) (coupling-subsystems '(horizontal-transport))))
    (t32-check "wall does not enter lift/barrier checks"
               (null (coupling-lift-barriers (coupling-fan-out controls) (traversal-arc-facts) table))))
  (let ((mc (with-output-to-string (*standard-output*) (report-mechanic-coverage)))
        (rc (with-output-to-string (*standard-output*) (report-relay-chain-table)))
        (nh (with-output-to-string (*standard-output*) (report-necessity-hints))))
    (t32-check "wall mechanic covered" (and (search "contract wall-blower" mc) (search "UNCOVERED (0)" mc)))
    (t32-check "authored width and default stream" (search "elevation 1; width 4" mc))
    (dolist (output (list rc nh))
      (t32-check "live station conflict reported" (search "LIVE STATION CONFLICT" output))
      (t32-check "recording sightlines explicitly unresolved"
                 (search "recording sightlines, body/view assignment and occupancy stability UNRESOLVED" output)))
    (t32-check "NH body bound scoped to geometric candidates" (search "within those geometric candidates" nh))
    (format t "~%WINDTUNNEL RC OUTPUT~%~A~%WINDTUNNEL NH OUTPUT~%~A" rc nh))
  (format t "~&T32 windtunnel checks passed; cumulative ~D~%" *t32-checks*))

(defun t32-mountable-checks ()
  (let ((state (copy-problem-state *start-state*)))
    (add-proposition '(turning wgears1) (problem-state.idb state))
    (funcall (symbol-function 'sweep-occupants-away!) state 'wgears1)
    (t32-check "present wall fan sweeps unit box at top boundary" (t32-fact-p state '(has-location box1 far)))
    (t32-check "sweep lands on flush plate" (t32-fact-p state '(on box1 plate2)))
    (t32-check "mounted fan remains mounted" (t32-fact-p state '(mounted-on fan1 wgears1)))
    (t32-check "wall fan has no standing location" (notany (lambda (fact) (and (eq (first fact) 'has-location)
                                                                                            (eq (second fact) 'fan1))) (database state))))
  (let ((state (copy-problem-state *start-state*)))
    (revise (problem-state.idb state) '((turning wgears1) (not (mounted-on fan1 wgears1)) (has-location fan1 mid)))
    (funcall (symbol-function 'sweep-occupants-away!) state 'wgears1)
    (t32-check "vacant turning gears do not sweep box" (t32-fact-p state '(has-location box1 mid)))
    (t32-check "loose zero-thickness fan stays" (t32-fact-p state '(has-location fan1 mid))))
  (let ((controls (control-facts)))
    (t32-check "mountable drive cannot prove always-present conflict"
               (null (relay-wall-required-gates 'wgears1 '(example-gate) controls (device-state-axioms controls)))))
  (let ((text (with-output-to-string (*standard-output*) (report-wall-blower-instances))))
    (t32-check "mountable contract kind and default dimensions"
               (and (search "removable fan required" text) (search "elevation 1; width 3" text))))
  (format t "~&T32 mountable checks passed; cumulative ~D~%" *t32-checks*))

(defun t32-high-stream-checks ()
  "This fixture authors stream elevation 2 before staging, not after static compilation."
  (let ((state (copy-problem-state *start-state*)))
    (add-proposition '(turning high-drive) (problem-state.idb state))
    (t32-check "authored high stream" (= 2 (funcall (symbol-function 'blower-elevation) state 'high-drive)))
    (t32-check "authored unit box top" (= 1 (funcall (symbol-function 'top) state 'low-box)))
    (funcall (symbol-function 'sweep-occupants-away!) state 'high-drive)
    (t32-check "real sweep leaves below-stream box" (t32-fact-p state '(has-location low-box source)))
    (t32-check "real sweep moves raised rider at inclusive top" (t32-fact-p state '(has-location high-box target)))
    (t32-check "raised rider detached from original support" (not (t32-fact-p state '(on high-box low-box)))))
  (format t "~&T32 high-stream checks passed; cumulative ~D~%" *t32-checks*))


(defun t32-floor-snapshot ()
  (list (with-output-to-string (*standard-output*)
          (report-mechanic-contract (find "floor-blower" *mechanic-contracts* :key #'first :test #'string=)))
        (let* ((controls (control-facts)) (arcs (traversal-arc-facts))
               (table (coupling-role-table controls arcs nil)))
          (list (coupling-roles 'blower1 table)
                (coupling-lift-barriers (coupling-fan-out controls) arcs table)))))

(defun t32-floor-checks (baseline)
  (t32-check "floor contract, instance output, roles and lift/barrier rows unchanged"
             (equal baseline (t32-floor-snapshot)))
  (t32-check "floor still has lift role" (member 'lift (first (second baseline))))
  (t32-check "floor lift/barrier analysis exercised" (second (second baseline)))
  (format t "~&T32 ALL CHECKS PASSED: ~D~%" *t32-checks*))

(t32-pure-checks)
