;;; Supplied scenarios, not reached states. No search, settling or replay.
(in-package :ww)
(defparameter *t33-checks* 0)
(defun t33-check (label passed)
  (unless passed (error "T33 failed: ~A" label))
  (incf *t33-checks*)
  (format t "~&PASS ~A~%" label))

(defun t33-scenario (state phase hops chains &optional premises)
  (list :state state :complete-state t :phase phase
        :provenance "T33 injected fixture; reference facts and gates are premises, not reached/settled state"
        :hops hops :chains chains :gate-premises premises))

(defun t33-status (results view)
  (getf (find view results :key (lambda (row) (getf row :view))) :status))

(defun t33-pure-checks ()
  (t33-check "no scenario is unresolved in both views"
             (every (lambda (row) (eq :unresolved (getf row :status))) (relay-view-results nil)))
  (t33-check "state missing" (search "reference" (relay-view-input-reason '(:phase :open))))
  (let ((scenario (t33-scenario (make-problem-state) :ordinary nil nil)))
    (t33-check "empty tests are unresolved" (search "no supplied" (relay-view-input-reason scenario)))
    (setf (getf scenario :hops) '((somewhere 1 endpoint 1)))
    (t33-check "schema accepts explicit scenario" (null (relay-view-input-reason scenario)))
    (remf scenario :chains)
    (t33-check "missing chains is distinct from empty" (search "keys missing" (relay-view-input-reason scenario)))
    (setf (getf scenario :complete-state) nil)
    (t33-check "partial state is unresolved" (search "complete-state" (relay-view-input-reason scenario)))))

(defun t33-wind-state ()
  (let ((state (copy-problem-state *start-state*)))
    (revise (problem-state.idb state)
            '((not (recorder-cycle-closed)) (recording-in-progress)
              (has-location agent1 location4) (has-location agent1* location4)
              (has-location connector1 location1) (has-location connector1* location3)
              (paired connector1 transmitter1) (paired connector1 repeater1)
              (paired connector1* repeater1) (paired connector1* receiver1)))
    (invalidate-problem-state-hash state)
    state))

(defun t33-wind-checks ()
  (let* ((state (t33-wind-state))
         (before (database state))
         (static-before (list-static-db))
         (scenario (t33-scenario state :open '((location1 1 transmitter1 1)) nil
                                 '((:physical gate1 t) (:recording gate1 nil)))))
    (dolist (split '((t nil) (nil t) (t t) (nil nil)))
      (setf (getf scenario :gate-premises)
            (list (list :physical 'gate1 (first split)) (list :recording 'gate1 (second split))))
      (let ((results (relay-view-results scenario)) (copy (relay-view-state scenario)))
        (when (not (first split))
          (t33-check "blocked gate named"
                     (search "GATE1" (getf (first (getf (first results) :hops)) :reason))))
        (loop for view in '(:physical :recording) for open in split
              for selector = (when (eq view :recording) 'connector1*)
              do (t33-check (format nil "gate split ~S ~A verdict" split view)
                             (eq (if open :clear :blocked) (t33-status results view)))
                 (t33-check "hop agrees with direct engine"
                            (eql open (not (null (beam-visible-for-object copy selector
                                                     'location1 1 'transmitter1 1))))))))
    (setf (getf scenario :gate-premises) '((:physical gate1 t) (:recording gate1 nil))
          (getf scenario :chains) '((transmitter1 connector1 repeater1 connector1* receiver1)))
    (let* ((results (relay-view-results scenario))
           (copy (relay-view-state scenario)))
      (t33-check "mixed ghost/live chain physical clear" (eq :clear (t33-status results :physical)))
      (t33-check "mixed chain recording blocked" (eq :blocked (t33-status results :recording)))
      (update-relay-status! copy)
      (t33-check "physical whole chain agrees with receiver engine" (relay-beam-reaches-receiver copy 'receiver1))
      (t33-check "recording whole chain agrees with receiver engine"
                 (not (recording-shadow-relay-beam-reaches-receiver
                        copy 'connector1* (compute-relay-lighting-for-object copy 'connector1* nil) 'receiver1))))
    (t33-check "original reference unchanged" (equal before (database state)))
    (t33-check "static facts unchanged" (equal static-before (list-static-db)))
    (let ((output (with-output-to-string (*standard-output*) (report-relay-view-scenario scenario))))
      (dolist (text '("PHYSICAL CLEAR" "RECORDING BLOCKED" "gate premises" "not stable/reachable/validated"))
        (t33-check (format nil "report contains ~A" text) (search text output))))
    (dolist (reporter '(report-relay-chain-table report-necessity-hints))
      (let ((output (with-output-to-string (*standard-output*) (funcall reporter scenario))))
        (t33-check (format nil "~A carries separate scenario views" reporter)
                   (and (search "PHYSICAL CLEAR" output) (search "RECORDING BLOCKED" output)))))
    (let ((results (relay-view-results scenario)))
      (t33-check "each view retains its premise provenance"
                 (every (lambda (result)
                          (and (equal (getf result :gate-premises) (getf scenario :gate-premises))
                               (equal (getf result :provenance) (getf scenario :provenance)))) results)))
    (let ((*spliced-tech-names* (remove "visibility" *spliced-tech-names* :test #'string=)))
      (t33-check "neutral visibility hook is unavailable, not blocked"
                 (eq :unresolved (t33-status (relay-view-results scenario) :physical))))
    (let ((invalid (copy-list scenario)) (unchanged (database state)))
      (setf (getf invalid :hops) '((no-such-location 1 transmitter1 1)))
      (t33-check "invalid hop diagnosed" (eq :invalid (t33-status (relay-view-results invalid) :physical)))
      (t33-check "invalid input preserves reference" (equal unchanged (database state)))
      (setf (getf invalid :hops) '((location1)))
      (t33-check "malformed input surfaces an error"
                 (handler-case (progn (relay-view-results invalid) nil) (error () t)))
      (t33-check "exception preserves reference" (equal unchanged (database state))))
    (setf (getf scenario :phase) :closed)
    (t33-check "contradictory phase unresolved" (eq :unresolved (t33-status (relay-view-results scenario) :physical)))
    (setf (getf scenario :phase) :open
          (getf scenario :gate-premises) '((:physical gate1 t) (:physical gate1 nil)))
    (t33-check "contradictory gate premises unresolved" (eq :unresolved (t33-status (relay-view-results scenario) :physical)))
    (setf (getf scenario :gate-premises) '((:physical gate1 t)))
    (revise (problem-state.idb state) '((paired connector1 receiver1)))
    (t33-check "pairing capacity enforced" (eq :invalid (t33-status (relay-view-results scenario) :physical)))
    (revise (problem-state.idb state) '((not (paired connector1 receiver1)) (not (paired connector1* receiver1)) (paired connector1* connector1)))
    (t33-check "ghost-to-live pairing rejected" (search "policy" (relay-view-pairing-reason state 'connector1* (relay-view-mappings))))
    (revise (problem-state.idb state) '((not (paired connector1* connector1))))
    (setf (getf scenario :chains) '((transmitter1 connector1 repeater1 connector1 receiver1)))
    (t33-check "identity cannot fill two chain stations" (eq :invalid (t33-status (relay-view-results scenario) :physical)))
    (setf (getf scenario :chains) nil (getf scenario :state) *start-state* (getf scenario :phase) :closed)
    (t33-check "closed recording context unresolved" (eq :unresolved (t33-status (relay-view-results scenario) :recording)))
    (let* ((missing (t33-wind-state))
           (absent (t33-scenario missing :open nil '((transmitter1 connector1 repeater1 connector1* receiver1))
                                  '((:physical gate1 t)))))
      (revise (problem-state.idb missing) '((not (has-location connector1* location3))))
      (t33-check "absent recorded connector blocked" (eq :blocked (t33-status (relay-view-results absent) :physical))))))

(defun t33-shadow-checks ()
  (let* ((state (copy-problem-state *start-state*))
         (before (database state))
         (scenario (t33-scenario state :shadow-only '((recording-relay-site 1 recording-receiver 1))
                                 '((recording-transmitter ghost-recording-connector recording-receiver)))))
    (let ((results (relay-view-results scenario)))
      (t33-check "mapped live blocker physical blocked" (eq :blocked (t33-status results :physical)))
      (t33-check "mapped live blocker absent recording clear" (eq :clear (t33-status results :recording)))
      (t33-check "blocked occluder named"
                 (search "BLOCKER-SITE" (getf (first (getf (first results) :hops)) :reason)))
      (t33-check "recording lighting matches direct engine"
                 (recording-shadow-relay-beam-reaches-receiver
                  state 'ghost-agent (compute-relay-lighting-for-object state 'ghost-agent nil) 'recording-receiver)))
    (revise (problem-state.idb state) '((has-location live-blocker spare-site) (has-location ghost-blocker blocker-site)))
    (t33-check "mapped ghost blocker blocks recording" (eq :blocked (t33-status (relay-view-results scenario) :recording)))
    (revise (problem-state.idb state) '((has-location ghost-blocker spare-site)))
    (t33-check "both blockers removed both views clear"
               (every (lambda (row) (eq :clear (getf row :status))) (relay-view-results scenario)))
    (setf (getf scenario :hops) nil
          (getf scenario :chains) '((playback-transmitter live-playback-connector playback-receiver)))
    (let ((results (relay-view-results scenario)))
      (t33-check "live relay physical available" (eq :clear (t33-status results :physical)))
      (t33-check "live relay absent recording" (eq :blocked (t33-status results :recording))))
    (t33-check "staged start unchanged" (equal before (database *start-state*)))))

(defun t33-ordinary-checks ()
  (let* ((state (copy-problem-state *start-state*))
         (scenario (t33-scenario state :ordinary '((target 1 new-source 1))
                                 '((new-source lifecycle-connector new-receiver)))))
    (revise (problem-state.idb state)
            '((not (on lifecycle-connector old-plate)) (has-location lifecycle-connector target)
              (not (paired lifecycle-connector old-source)) (not (paired incoming-connector lifecycle-connector))
              (paired lifecycle-connector new-source) (paired lifecycle-connector new-receiver)))
    (let ((results (relay-view-results scenario)))
      (t33-check "ordinary physical chain clear" (eq :clear (t33-status results :physical)))
      (t33-check "ordinary recording context unavailable" (eq :unresolved (t33-status results :recording))))
    (update-relay-status! state)
    (t33-check "ordinary engine receiver agrees" (relay-beam-reaches-receiver state 'new-receiver))))

(t33-pure-checks)
