(in-package :ww)
(defparameter *t34-checks* 0)
(defun t34-check (label passed)
  (unless passed (error "T34 failed: ~A" label))
  (incf *t34-checks*)
  (format t "~&PASS ~A~%" label))

(defun t34-scenario (state phase receiver chain)
  (list :state state :complete-state t :phase phase :receiver receiver :view :physical
        :provenance "T34 supplied fixture, not independently found/reached; controller and configuration premises"
        :hops nil :chains (list chain)))

(defun t34-check-preserved (scenario)
  (let* ((source (getf scenario :state))
         (snapshot (arrangement-state-snapshot source))
         (static (copy-tree (list-static-db)))
         (tables (mapcar (lambda (table)
                           (loop for key being the hash-keys of table using (hash-value value)
                                 collect (cons key (copy-tree value))))
                         (list *types* *relations* *static-relations*)))
         (data (copy-tree scenario))
         (result (check-relay-arrangement scenario)))
    (t34-check "caller scenario preserved" (equal data scenario))
    (t34-check "reference fully preserved" (equal snapshot (arrangement-state-snapshot source)))
    (t34-check "static database preserved" (equal static (list-static-db)))
    (t34-check "type and relation tables preserved"
               (equal tables (mapcar (lambda (table)
                                       (loop for key being the hash-keys of table using (hash-value value)
                                             collect (cons key (copy-tree value))))
                                     (list *types* *relations* *static-relations*))))
    result))

(defun t34-wind-state (physical recording)
  (let ((state (t33-wind-state)))
    (revise (problem-state.idb state)
            (list (if physical '(latched plate1) '(not (latched plate1)))
                  (if recording '(recording-latched plate1) '(not (recording-latched plate1)))))
    state))

(defun t34-live-ground-state ()
  "Swap the two relay roles, preserving the geometric path before the live sweep."
  (let ((state (t34-wind-state t nil)))
    (revise (problem-state.idb state)
            '((has-location connector1 location3) (has-location connector1* location1)
              (not (paired connector1 transmitter1)) (paired connector1 receiver1)
              (not (paired connector1* receiver1)) (paired connector1* transmitter1)))
    state))

(defun t34-live-ground-check ()
  (let* ((scenario (t34-scenario (t34-live-ground-state) :open 'receiver1
                                 '(transmitter1 connector1* repeater1 connector1 receiver1)))
         (geometry (copy-list scenario)))
    (setf (getf geometry :gate-premises) '((:physical gate1 t)))
    (t34-check "swapped live-ground chain is geometrically clear before settling"
               (eq :clear (getf (first (relay-view-results geometry)) :status)))
    (let ((result (t34-check-preserved scenario)))
      (t34-check "geometrically clear live-ground chain fails after settling"
                 (eq :settled-but-failed (getf result :status)))
      (t34-check "live station displacement explicitly reported"
                 (member '(has-location connector1 location3)
                         (getf (getf result :configuration-changes) :removed) :test #'equal)))))

(defun t34-wind-checks ()
  (t34-check "missing scenario unresolved" (eq :unresolved (getf (check-relay-arrangement nil) :status)))
  (t34-check "malformed top-level input unresolved"
             (eq :unresolved (getf (check-relay-arrangement 'not-a-plist) :status)))
  (t34-check "malformed plist reports input exception"
             (eq :input-check (getf (check-relay-arrangement '(:state)) :stage)))
  (t34-check "reporter preserves malformed-input diagnostic"
             (search "UNRESOLVED" (with-output-to-string (*standard-output*)
                                     (report-relay-arrangement 'not-a-plist))))
  (let* ((state (t34-wind-state t nil))
         (scenario (t34-scenario state :open 'receiver1 '(transmitter1 connector1 repeater1 connector1* receiver1)))
         (result (t34-check-preserved scenario)))
    (format t "~&WIND RESULT ~S~%" (getf result :reason))
    (t34-check "mixed-view arrangement stable and lit" (eq :stable-and-beam-working (getf result :status)))
    (t34-check "second pass unchanged" (getf result :idempotent))
    (t34-check "physical receiver actually active" (getf result :receiver-active))
    (t34-check "gate and fan derived from primitive latch"
               (and (member '(open gate1) (database (getf result :settled-state)) :test #'equal)
                    (member '(turning blower1) (database (getf result :settled-state)) :test #'equal)))
    (setf (getf scenario :view) :recording)
    (t34-check "same arrangement fails recording beam" (eq :settled-but-failed (getf (t34-check-preserved scenario) :status))))
  (let* ((state (t34-wind-state nil nil))
         (scenario (t34-scenario state :open 'receiver1 '(transmitter1 connector1 repeater1 connector1* receiver1)))
         (result (t34-check-preserved scenario)))
    (t34-check "stationary unlit arrangement distinguished" (eq :settled-but-failed (getf result :status)))
    (t34-check "unlit arrangement has no motion"
               (equal '(:removed nil :added nil) (getf result :configuration-changes))))
  (dolist (split '((t nil) (nil t) (t t)))
    (let* ((state (t34-wind-state (first split) (second split)))
           (scenario (t34-scenario state :open 'receiver1 '(transmitter1 connector1 repeater1 connector1* receiver1))))
      (revise (problem-state.idb state) '((has-location connector1 location3)))
      (let* ((result (t34-check-preserved scenario)) (settled (getf result :settled-state)))
        (t34-check (format nil "sweep split ~S settles but changes arrangement" split)
                   (eq :settled-but-failed (getf result :status)))
        (t34-check "live follows physical fan"
                   (member (list 'has-location 'connector1 (if (first split) 'location6 'location3))
                           (database settled) :test #'equal))
        (t34-check "ghost follows recording fan"
                   (member (list 'has-location 'connector1* (if (second split) 'location6 'location3))
                           (database settled) :test #'equal)))))
  (let* ((state (t34-wind-state t nil))
         (scenario (t34-scenario state :open 'receiver1 '(transmitter1 connector1 repeater1 connector1* receiver1))))
    (setf (getf scenario :gate-premises) '((:physical gate1 t)))
    (t34-check "forced derived bits refused" (eq :unresolved (getf (t34-check-preserved scenario) :status)))
    (remf scenario :gate-premises)
    (revise (problem-state.idb state) '((paired connector1 receiver1)))
    (t34-check "invalid pairing capacity" (eq :invalid (getf (t34-check-preserved scenario) :status)))))

(defun t34-edge-memory-check ()
  (let* ((state (t34-wind-state t nil))
         (scenario (t34-scenario state :open 'receiver1 '(transmitter1 connector1 repeater1 connector1* receiver1))))
    (revise (problem-state.idb state)
            '((has-location agent1 location2) (on agent1 plate1) (depressed plate1)))
    (let ((result (t34-check-preserved scenario)))
      (t34-check "already depressed toggle not pressed twice" (eq :stable-and-beam-working (getf result :status)))
      (t34-check "physical latch preserved by edge memory"
                 (member '(latched plate1) (database (getf result :settled-state)) :test #'equal)))))

(defun t34-fixture-scenario (state)
  (t34-scenario state :ordinary 'target '(source relay target)))

(defun t34-fixture-checks ()
  (let ((result (t34-check-preserved (t34-fixture-scenario *start-state*))))
    (t34-check "ordinary baseline intact and lit" (eq :stable-and-beam-working (getf result :status))))
  (let* ((state (copy-problem-state *start-state*))
         (scenario (t34-fixture-scenario state)))
    (revise (problem-state.idb state) '((latched loop-control)))
    (let* ((result (t34-check-preserved scenario)) (facts (database (getf result :settled-state))))
      (t34-check "support stack displacement fails requested configuration" (eq :settled-but-failed (getf result :status)))
      (t34-check "base and rider swept together"
                 (and (member '(has-location pedestal delivered) facts :test #'equal)
                      (member '(has-location rider delivered) facts :test #'equal)
                      (member '(on rider pedestal) facts :test #'equal)))
      (t34-check "controller feedback closes needed gate" (not (member '(open shutter) facts :test #'equal)))
      (t34-check "changed gate extinguishes actual receiver" (not (getf result :receiver-active)))))
  (let* ((state (copy-problem-state *start-state*)))
    (revise (problem-state.idb state) '((has-location pedestal hover-site) (has-location rider hover-site)))
    (let* ((result (t34-check-preserved (t34-fixture-scenario state)))
           (facts (database (getf result :settled-state))))
      (t34-check "unsupported hover drops" (eq :settled-but-failed (getf result :status)))
      (t34-check "floor drop preserves stack links"
                 (and (member '(has-location pedestal floor-site) facts :test #'equal)
                      (member '(has-location rider floor-site) facts :test #'equal)
                      (member '(on rider pedestal) facts :test #'equal)))))
  (let ((state (copy-problem-state *start-state*)))
    (revise (problem-state.idb state) '((has-location pedestal loop-a) (has-location rider loop-a) (latched loop-control)))
    (let ((result (t34-check-preserved (t34-fixture-scenario state))))
      (t34-check "actual active transport loop hits existing bound" (eq :inconsistent (getf result :status)))))
  (dolist (change '(((on pedestal rider))
                    ((has-location rider safe))
                    ((holding worker relay))
                    ((on relay tray))
                    ((on relay pedestal) (has-location relay swept))
                    ((paired relay worker))
                    ((has-location puck safe))
                    ((not (has-location relay beam-site)))))
    (let ((state (copy-problem-state *start-state*)))
      (revise (problem-state.idb state) change)
      (let ((result (t34-check-preserved (t34-fixture-scenario state))))
        (t34-check (format nil "invalid configuration ~S" change) (eq :invalid (getf result :status)))))))

(defun t34-exception-checks ()
  "Fault injection at the diagnostic's propagation boundary, restored even on failure."
  (let ((original (symbol-function 'arrangement-propagate))
        (scenario (t34-fixture-scenario *start-state*)))
    (unwind-protect
        (progn
          (setf (symbol-function 'arrangement-propagate)
                (lambda (state)
                  (delete-proposition '(has-location relay beam-site) (problem-state.idb state))
                  (error "T34 injected propagation interruption")))
          (let ((result (t34-check-preserved scenario)))
            (t34-check "exception returns unresolved" (eq :unresolved (getf result :status)))
            (t34-check "exception retains cause and stage"
                       (and (eq :consequence-or-beam-evaluation (getf result :stage))
                            (search "injected" (getf result :reason))))))
      (setf (symbol-function 'arrangement-propagate) original))
    (unwind-protect
        (progn
          (setf (symbol-function 'arrangement-propagate)
                (lambda (state) (prog1 (funcall original state) (incf (problem-state.time state)))))
          (let ((result (t34-check-preserved scenario)))
            (t34-check "second-pass metadata drift is unresolved" (eq :unresolved (getf result :status)))
            (t34-check "drift is not a stable result" (not (getf result :idempotent)))))
      (setf (symbol-function 'arrangement-propagate) original))))

(defun t34-held-tray-checks ()
  (let* ((state (copy-problem-state *start-state*))
         (scenario (t34-scenario state :open 'target '(source live-connector target)))
         (reason (arrangement-validation-reason state :open)))
    (t34-check "runtime live-on-ghost-held-tray is structurally valid" (null reason))
    (let ((result (t34-check-preserved scenario)))
      (t34-check "held-tray scenario reaches consequence evaluation"
                 (member (getf result :status) '(:stable-and-beam-working :settled-but-failed))))
    (revise (problem-state.idb state) '((not (on live-connector ghost-tray))
                                       (not (on ghost-connector ghost-tray))
                                       (on live-holder ghost-tray) (on ghost-holder live-tray)))
    (let ((result (t34-check-preserved scenario)))
      (t34-check "mixed support/holding cycle rejected before TOP recursion" (eq :invalid (getf result :status)))
      (t34-check "cycle named" (search "cycle" (getf result :reason))))))
