;;; T36 extra DNF oracle and hint checks; load after t36-reachability-checks.
(in-package :ww)
(defun t36-alternative-checks ()
  (let ((regions '("A" "B" "C")))
    (dolist (style '(0 1 2 3))
      (dotimes (mask 64)
        (let ((rows nil) (bit 0))
          (dolist (from regions)
            (dolist (to regions)
              (unless (equal from to)
                (when (logbitp bit mask)
                  (push (list from to 'walk
                              (case (mod (+ bit style) 4)
                                (0 '((d1) (d2))) (1 '((d1 d3) (d2 d3)))
                                (2 '(nil (d1))) (3 nil))
                              (if (evenp style) :forward :both) 1) rows))
                (incf bit))))
          (let ((before (copy-tree rows)))
            (t36-graph-check rows regions '(d1 d2 d3))
            (t36-check "DNF input unchanged" (equal before rows))))))
    (let ((rows '(("A" "B" walk ((d1) (d2)) :forward 1))))
      (t36-check "either alternative survives the other's exclusion"
                 (and (equal '("A" "B") (keeper-reachable "A" rows 'd1))
                      (equal '("A" "B") (keeper-reachable "A" rows 'd2))))
      (t36-check "alternatives do not reverse a directed row"
                 (equal '("B") (keeper-reachable "B" rows nil))))
    (let ((rows '(("A" "B" walk ((d1 d3) (d2 d3)) :both 1))))
      (t36-check "shared door blocks every clause"
                 (and (equal '("A") (keeper-reachable "A" rows 'd3))
                      (equal '("A" "B") (keeper-reachable "A" rows 'd1)))))
    (let ((rows '(("A" "B" walk (nil (d1)) :both 1))))
      (t36-check "empty clause remains door-free"
                 (equal '("A" "B") (keeper-reachable "B" rows 'd1))))
    (let* ((rows '(("A" "B" walk ((d1)) :forward 1)
                   ("A" "C" walk ((d3)) :forward 1)
                   ("C" "B" walk nil :forward 1)))
           (reason (quotient-reachability-mismatch rows (rest rows) regions '(d1))))
      (t36-check "final guard includes uncontrolled row doors"
                 (equal '(:reachability-mismatch "A" d3) reason))))
  (format t "~&T36 DNF oracle checks passed; cumulative ~D~%" *t36-checks*))
(defun t36-h2-alternatives ()
  (let* ((names (make-hash-table :test #'eq))
         (position (keeper-fact-value 'has-position 'plate1 (list-static-db)))
         (row '("A" "B" walk ((d1) (d2)) :forward 1))
         (fact '(controls ((plate1)) d1 normal))
         (context (list :spine (list row) :names names
                        :blocks '(("A" (location2)) ("B" (location3))))))
    (setf (gethash position names) "A")
    (t36-check "alternative row does not make an optional device necessary"
               (null (hint-keeper-row fact "A" "B" row context nil)))
    (let ((required '("A" "B" walk ((d1 d2) (d1 d3)) :forward 1)))
      (setf (getf context :spine) (list required))
      (t36-check "door shared by all alternatives can require a keeper"
                 (hint-keeper-row fact "A" "B" required context nil)))))
(defun t36-claustro-checks ()
  (let* ((controls (control-facts))
         (context (hint-route-context controls))
         (rows (quotient-arc-rows (getf context :arcs) (getf context :names)))
         (regions (mapcar #'first (getf context :blocks)))
         (families (necessity-hint-families controls context))
         (report (with-output-to-string (*standard-output*) (report-cut-keeper-table)))
         (nh (with-output-to-string (*standard-output*)
               (report-necessity-hint-families families context))))
    (t36-check "claustro has alternative families" (quotient-alternative-families-p rows))
    (t36-check "claustro no S4 failure" (null (getf context :spine-reason)))
    (t36-check "claustro retains every row" (= (length rows) (length (getf context :spine))))
    (t36-graph-check rows regions
                     (remove-duplicates (append (mapcar #'third controls)
                                                (mapcan #'quotient-row-doors rows))))
    (t36-check "unreduced strategy explicit" (search "using the unreduced quotient" report))
    (t36-check "verified spine" (search ":VERIFIED-AGAINST-QUOTIENT" report))
    (dolist (device '(gate8 gate9))
      (let ((row (with-output-to-string (*standard-output*)
                   (report-keeper-device (find device controls :key #'third)
                     (getf context :spine) nil (list-static-db) (getf context :names)
                     (device-state-axioms controls) (census-type-instances 'pressure-plate)))))
        (t36-check (list device "directional verdict") (search "graph cut in this direction:" row))))
    (t36-check "H2/H4 available" (not (search "UNAVAILABLE" nh)))
    (t36-check "H2 evaluated into real hints" (plusp (length (second families))))
    (format t "~&Claustro rows ~D; H2 ~D hints; H4 ~D hints (valid empty allowed).~%"
            (length rows) (length (second families)) (length (fourth families)))))

