;;; T38 acceptance: stage problem-t38-probe.lisp first, then load profile, PB and this file.
(in-package :ww)
(defvar *t38-count* 0)
(defun t38-check (name value)
  (assert value () "T38 failure: ~A" name)
  (incf *t38-count*)
  (format t "~&PASS ~A~%" name))
(defun t38-path (name)
  (merge-pathnames name (asdf:system-source-directory :wouldwork)))
(defun t38-report (path)
  (with-output-to-string (*standard-output*) (report-probe-battery path)))
(defun t38-probe (goal)
  (list :id "P5.1" :family 5 :subject 'fixture :goal goal :provenance "T38 fixture"))
(defun t38-run (depth goal expected)
  (let* ((path (t38-path "doc/constraint-method/evidence/t38-probe-results-2026-09-27.lisp"))
         (state (make-subgoal-progress-state-signature *start-state*))
         (goal-before (copy-tree *goal*))
         (goal-form (copy-tree (get 'goal-fn :form)))
         (goal-result (funcall (symbol-function 'goal-fn) *start-state*))
         (cutoff *depth-cutoff*) (mode *solution-type*) (undo *undo-stack*))
    (run-probe-battery depth path (list (t38-probe goal)))
    (let* ((results (read-probe-battery-results path))
           (record (first (getf results :probes)))
           (report (t38-report path)))
      (t38-check (list goal depth expected) (eq expected (getf record :label)))
      (t38-check "no cap in new settings" (not (member :states-limit (getf results :settings))))
      (t38-check "new report has no obsolete output"
                 (and (not (search "states limit" report)) (not (search "STOPPED" report))))
      (t38-check "settings and session restored"
                 (and (= cutoff *depth-cutoff*) (eq mode *solution-type*)
                      (eq undo *undo-stack*) (equal goal-before *goal*)
                      (equal goal-form (get 'goal-fn :form))
                      (eql goal-result (funcall (symbol-function 'goal-fn) *start-state*))
                      (equalp state (make-subgoal-progress-state-signature *start-state*))))
      (when (eq expected :cheap)
        (let* ((plan (getf (car (last (getf record :runs))) :plan))
               (validation (validate-action-sequence *start-state* plan
                             :goal-test (symbol-function 'goal-fn))))
          (t38-check "two-action result replays to original goal"
                     (and (= 2 (length plan))
                          (action-sequence-validation-success-p validation)
                          (action-sequence-validation-goal-checked-p validation)
                          (action-sequence-validation-goal-satisfied-p validation)))))
      record)))
(defun t38-large-counts ()
  (let ((old-start (symbol-function 'probe-goal-holds-at-start-p))
        (old-run (symbol-function 'probe-run-once)) (cutoffs nil))
    (unwind-protect
        (progn
          (setf (symbol-function 'probe-goal-holds-at-start-p)
                (lambda (goal checkpoint) (declare (ignore goal checkpoint)) nil)
                (symbol-function 'probe-run-once)
                (lambda (checkpoint goal cutoff)
                  (declare (ignore checkpoint goal))
                  (push cutoff cutoffs)
                  (list :cutoff cutoff :found nil :truncated t
                        :states (expt 10 30))))
          (let ((record (probe-deepen nil (t38-probe '(at unreachable)) 4)))
            (t38-check "huge state counts do not stop deepening"
                       (and (equal (reverse cutoffs) '(1 2 3 4))
                            (eq :not-found (getf record :label))
                            (= 4 (length (getf record :runs)))))))
      (setf (symbol-function 'probe-goal-holds-at-start-p) old-start
            (symbol-function 'probe-run-once) old-run))))
(defun t38-legacy ()
  (dolist (name '("t23-probe-battery-results-2026-09-26.lisp"
                  "t23-pb-negative-2026-09-26.lisp"
                  "t29-d-probes-results-2026-09-26.lisp"))
    (let ((report (t38-report (t38-path (concatenate 'string "doc/constraint-method/evidence/" name)))))
      (t38-check (list "historical report" name) (search "PB  PROBE BATTERY" report))))
  (let ((path (t38-path ".t38-work/legacy.lisp")))
    (write-probe-battery-results path
      '(:problem historic :max-depth 4 :states-limit 1 :threads 16 :solution-type first)
      (list (append (t38-probe '(at unreachable))
                    '(:label :stopped :runs ((:cutoff 1 :states 2 :truncated t))))))
    (let ((report (t38-report path)))
      (t38-check "legacy STOPPED remains ungraded and counted"
                 (and (search "1 LEGACY STOPPED (no bound claimed)" report)
                      (search "LEGACY STOPPED at 1  [none]" report)
                      (not (search "states limit" report)))))
    (delete-file path)))
(defun t38-error-restoration ()
  (let ((old-run (symbol-function 'probe-run-once))
        (cutoff *depth-cutoff*) (mode *solution-type*)
        (goal-result (funcall (symbol-function 'goal-fn) *start-state*)) (undo *undo-stack*) (caught nil))
    (unwind-protect
        (progn
          (setf (symbol-function 'probe-run-once)
                (lambda (&rest args) (declare (ignore args))
                  (setf *depth-cutoff* 123 *solution-type* 'first)
                  (error "T38 injected failure")))
          (handler-case
              (run-probe-battery 2 (t38-path ".t38-work/failure.lisp")
                                 (list (t38-probe '(at finish))))
            (error () (setf caught t))))
      (setf (symbol-function 'probe-run-once) old-run))
    (t38-check "exception restores settings and goal"
               (and caught (= cutoff *depth-cutoff*) (eq mode *solution-type*)
                    (eql goal-result (funcall (symbol-function 'goal-fn) *start-state*)) (eq undo *undo-stack*)))))
(defun t38-checks ()
  (setf *t38-count* 0)
  (t38-check "START has no runs" (null (getf (t38-run 3 '(at begin) :start) :runs)))
  (t38-run 0 '(at begin) :start)
  (t38-check "zero depth false goal has no runs"
             (null (getf (t38-run 0 '(at finish) :not-found) :runs)))
  (t38-run 1 '(at finish) :not-found)
  (t38-run 4 '(at unreachable) :exhausted)
  (t38-large-counts)
  (t38-legacy)
  (t38-error-restoration)
  (dolist (depth '(-1 1/2))
    (t38-check (list "invalid depth rejected" depth)
      (handler-case (progn (run-probe-battery depth "unused" nil) nil)
        (type-error () t))))
  (t38-run 3 '(at finish) :cheap)
  (format t "~&T38 CHECKS PASSED: ~D~%" *t38-count*))
(t38-checks)


