;;; T40 focused checks; stage corner-topo and load tech/constraint-profile.lisp first.
;;; No search.  Reference states replay prefixes of the validated corner-topo trace; the
;;; gate fixtures are hand-edited supplied arrangements settled by the engine's own
;;; propagation on private copies before evaluation.
(in-package :ww)
(defvar *t40-count* 0)
(defun t40-check (label value)
  (assert value () "T40 failed: ~A" label)
  (incf *t40-count*)
  (format t "~&PASS ~A~%" label))
(defun t40-text (function &rest arguments)
  (with-output-to-string (*standard-output*) (apply function arguments)))
(defun t40-row (from to)
  (find-if (lambda (row) (and (eq (first row) from) (eq (third row) to))) (crossing-beam-rows)))
(defun t40-beam (result from to)
  (find-if (lambda (beam) (and (eq (getf beam :from) from) (eq (getf beam :to) to))) (getf result :beams)))
(defun t40-label (result from to crossing)
  (second (assoc crossing (getf (t40-beam result from to) :crossings))))
(defun t40-prefix-state (count)
  (load (merge-pathnames "doc/problems/corner-topo/constraint-evidence/full-path/candidate-actions.lisp"
                         (asdf:system-source-directory :wouldwork)))
  (let ((validation (validate-action-sequence *start-state*
                                              (subseq (symbol-value '*corner-topo-candidate*) 0 count))))
    (t40-check (list "reference prefix replays" count) (action-sequence-validation-success-p validation))
    (action-sequence-validation-final-state validation)))
(defun t40-settled-fixture (remove add)
  (let ((state (copy-problem-state *start-state*)))
    (dolist (fact remove) (delete-proposition fact (problem-state.idb state)))
    (dolist (fact add) (add-proposition fact (problem-state.idb state)))
    (invalidate-problem-state-hash state)
    (let ((*applying-init-action* nil))
      (funcall (symbol-function 'propagate-changes!) state))
    (t40-check (list "fixture settles consistently" add) (not (state-is-inconsistent state)))
    state))
(defun t40-facts (state)
  (sort (mapcar #'prin1-to-string (list-database (problem-state.idb state))) #'string<))
(defun t40-result (state provenance)
  (let* ((before (t40-facts state))
         (result (beam-crossing-scenario-result (list :state state :provenance provenance))))
    (t40-check (list "caller state unchanged" provenance) (equal before (t40-facts state)))
    (t40-check (list "evaluated" provenance) (eq :evaluated (getf result :status)))
    (t40-check (list "engine fixed point" provenance) (getf result :fixed-point))
    result))
(defun t40-agreement (state result)
  "Every reported live beam and label agrees with the engine's own queries."
  (let* ((active (funcall (symbol-function 'current-crossing-set) state))
         (lighting (funcall (symbol-function 'compute-relay-lighting) state active)))
    (t40-check "active set is the stored CROSSING-ACTIVE set"
               (equal (keeper-sorted-set active) (getf result :active)))
    (dolist (row (crossing-canonical-rows (crossing-beam-rows)))
      (let* ((live (cond ((funcall (symbol-function 'beam-live-for-cutting) state (first row) (third row) lighting)
                          (list (first row) (third row)))
                         ((funcall (symbol-function 'beam-live-for-cutting) state (third row) (first row) lighting)
                          (list (third row) (first row)))))
             (from (first live)) (to (second live))
             (ids (second (t40-row from to)))
             (beam (and live (t40-beam result from to))))
          (t40-check (list "beam reported once iff engine live, in its trial orientation" row)
                     (and (eq (not (null beam)) (not (null live)))
                          (not (and live (t40-beam result to from)))))
          (when beam
            (t40-check (list "cut agrees" from to)
                       (eq (not (null (getf beam :cut)))
                           (not (null (funcall (symbol-function 'beam-cut) state from to)))))
            (dolist (crossing ids)
              (let ((reached (funcall (symbol-function 'beam-reaches-crossing)
                                      state from to crossing active lighting))
                    (label (t40-label result from to crossing)))
                (t40-check (list "label agrees with engine reaching" from to crossing)
                           (if reached
                             (or (string= label "ACTIVE") (eql 0 (search "REACHED, INACTIVE" label)))
                             (or (search "BEYOND CUT" label) (search "BEYOND CLOSED" label))))
                (t40-check (list "no unexplained label" crossing) (not (search "UNEXPLAINED" label)))
                (t40-check (list "ACTIVE iff stored active" crossing)
                           (eq (string= label "ACTIVE") (not (null (member crossing active))))))))))))

(defun t40-static-checks ()
  (let* ((rows (crossing-beam-rows))
         (pool (crossing-pool))
         (text (t40-text #'report-beam-crossing-instances))
         (positions (funcall (symbol-function 'beam-coordinates-endpoint-positions) *start-state*))
         (records (beam-coordinates-crossing-records
                    (funcall (symbol-function 'beam-coordinates-potential-beams) *start-state*)
                    positions pool)))
    (t40-check "pool of 37 published" (= 37 (length pool)))
    (t40-check "every stored beam is reported in stored order"
               (every (lambda (row) (search (crossing-sequence-text (first row) (second row) (third row) rows) text))
                      rows))
    (dolist (beam '((transmitter1 location4) (transmitter2 location2) (location2 receiver1) (location3 receiver1)
                    (transmitter1 location1) (location1 location4) (location4 location1)))
      (let ((row (t40-row (first beam) (second beam))))
        (t40-check (list "relevant corner segment present" beam) row)
        (t40-check (list "row text lists stored order" beam)
                   (let ((line (crossing-sequence-text (first row) (second row) (third row) rows))
                         (start 0))
                     (every (lambda (crossing)
                              (let ((at (search (format nil "~(~A~) " crossing) line :start2 start)))
                                (and at (setf start (1+ at)))))
                            (second row))))))
    (t40-check "transmitter1->location4 source order"
               (equal '(crossing10 crossing7 crossing15 crossing14 crossing13 crossing12 crossing11)
                      (second (t40-row 'transmitter1 'location4))))
    (t40-check "transmitter2->location2 source order"
               (equal '(crossing1 crossing7 crossing9 crossing8) (second (t40-row 'transmitter2 'location2))))
    (t40-check "gate1 after all transmitter1->location4 crossings"
               (search "crossing11 (x location1->receiver2), |gate1|" text))
    (t40-check "gate1 after all transmitter2->location4 crossings"
               (search "crossing17 (x location2->receiver1), |gate1|" text))
    (t40-check "gate1 first on location4->location1" (search "location4->location1: |gate1|, crossing30" text))
    (t40-check "gate1 last on location1->location4" (search "crossing30 (x location2->receiver1), |gate1|" text))
    (t40-check "location-to-location reverse order"
               (equal (second (t40-row 'location1 'location3)) (reverse (second (t40-row 'location3 'location1)))))
    (dolist (crossing pool)
      (t40-check (list "crossing on exactly two canonical beams" crossing)
                 (= 2 (count-if (lambda (row) (member crossing (second row))) (crossing-canonical-rows rows)))))
    (dolist (row (crossing-canonical-rows rows))
      (let ((parameters (loop for crossing in (second row)
                              for record = (assoc crossing records)
                              collect (if (equal (second record) (list (first row) (third row)))
                                        (third record) (fifth record)))))
        (t40-check (list "engine parameters increase along stored order" (first row) (third row))
                   (and (every #'realp parameters) (apply #'< parameters)))))
    (t40-check "crossing7 point" (search "crossing7 at (9.75,2.08)" text))
    (t40-check "crossing8 point" (search "crossing8 at (9.27,5.91)" text))
    (t40-check "no split missing on corner" (not (search "unsplit" text)))
    (t40-check "possible, not active" (search "none is claimed active" text))))

(defun t40-inactive-checks ()
  (let ((start (t40-result (copy-problem-state *start-state*) "corner start state")))
    (t40-agreement *start-state* start)
    (t40-check "start: no live beam" (null (getf start :beams)))
    (t40-check "start: no active crossing" (null (getf start :active))))
  (let* ((state (t40-prefix-state 2)) (result (t40-result state "corner trace prefix 2")))
    (t40-agreement state result)
    (t40-check "prefix 2: only transmitter1->location1 live"
               (and (= 1 (length (getf result :beams))) (t40-beam result 'transmitter1 'location1)))
    (dolist (crossing '(crossing2 crossing1 crossing3))
      (t40-check (list "prefix 2: reached, other beam not live" crossing)
                 (and (search "REACHED, INACTIVE" (t40-label result 'transmitter1 'location1 crossing))
                      (search "NOT LIVE" (t40-label result 'transmitter1 'location1 crossing)))))))

(defun t40-shield-checks ()
  (let* ((state (t40-prefix-state 14)) (result (t40-result state "corner trace prefix 14")))
    (t40-agreement state result)
    (t40-check "prefix 14: crossing7 is the only active crossing" (equal '(crossing7) (getf result :active)))
    (t40-check "prefix 14: transmitter1->location4 cut" (getf (t40-beam result 'transmitter1 'location4) :cut))
    (t40-check "prefix 14: transmitter2->location2 cut" (getf (t40-beam result 'transmitter2 'location2) :cut))
    (dolist (crossing '(crossing15 crossing14 crossing13 crossing12 crossing11))
      (t40-check (list "prefix 14: shielded beyond crossing7" crossing)
                 (string= "BEYOND CUT at crossing7" (t40-label result 'transmitter1 'location4 crossing))))
    (t40-check "prefix 14: crossing12 reached by location2->receiver1, other beam not reaching"
               (search "NOT REACHING (BEYOND CUT at crossing7)"
                       (t40-label result 'location2 'receiver1 'crossing12)))
    (t40-check "prefix 14: location2->receiver1 uncut" (not (getf (t40-beam result 'location2 'receiver1) :cut)))
    (t40-check "prefix 14: receiver1 active, gate1 open"
               (and (member '(active receiver1) (list-database (problem-state.idb state)) :test #'equal)
                    (equal '(gate1) (getf result :open-gates))))
    (t40-check "prefix 14 report" (search "crossing7: transmitter1->location4 x transmitter2->location2"
                                          (t40-text #'report-beam-crossing-scenario
                                                    (list :state state :provenance "prefix 14")))))
  (let* ((state (t40-prefix-state 15)) (result (t40-result state "corner trace prefix 15")))
    (t40-agreement state result)
    (t40-check "prefix 15: no active crossing" (null (getf result :active)))
    (t40-check "prefix 15: transmitter2->location2 uncut" (not (getf (t40-beam result 'transmitter2 'location2) :cut)))))

(defun t40-gate-checks ()
  (let* ((state (t40-settled-fixture
                  '((has-location connector2 location2))
                  '((has-location connector2 location4) (paired connector1 transmitter1)
                    (paired connector2 transmitter2))))
         (result (t40-result state "fixture: before closed gate")))
    (t40-agreement state result)
    (t40-check "before-gate fixture: gate1 closed" (equal '(gate1) (getf result :closed-gates)))
    (t40-check "before-gate fixture: crossing3 active on the source side of closed gate1"
               (equal '(crossing3) (getf result :active)))
    (t40-check "before-gate fixture: transmitter2->location4 cut" (getf (t40-beam result 'transmitter2 'location4) :cut))
    (t40-check "before-gate fixture: later crossings beyond cut"
               (string= "BEYOND CUT at crossing3" (t40-label result 'transmitter2 'location4 'crossing20))))
  (let* ((state (t40-settled-fixture
                  '((has-location connector2 location2))
                  '((has-location connector2 location4) (paired connector3 transmitter2)
                    (paired connector3 receiver1) (paired connector2 connector3) (paired connector2 connector1))))
         (result (t40-result state "fixture: beyond closed gate")))
    (t40-agreement state result)
    (t40-check "beyond-gate fixture: gate1 closed" (equal '(gate1) (getf result :closed-gates)))
    (t40-check "beyond-gate fixture: location4->location1 live" (t40-beam result 'location4 'location1))
    (dolist (crossing '(crossing30 crossing36))
      (t40-check (list "beyond-gate fixture: beyond closed gate1" crossing)
                 (string= "BEYOND CLOSED gate1" (t40-label result 'location4 'location1 crossing))))
    (t40-check "beyond-gate fixture: crossing36 reached by location3->receiver1, inactive for the gate"
               (search "NOT REACHING (BEYOND CLOSED gate1)" (t40-label result 'location3 'receiver1 'crossing36)))
    (t40-check "beyond-gate fixture: crossing36 inactive" (not (member 'crossing36 (getf result :active))))
    (t40-check "beyond-gate fixture: location3<->location4, live both ways, reported once from location3"
               (and (t40-beam result 'location3 'location4) (not (t40-beam result 'location4 'location3))))))

(defun t40-unresolved-checks ()
  (let ((edited (copy-problem-state *start-state*)))
    (add-proposition '(paired connector1 transmitter1) (problem-state.idb edited))
    (invalidate-problem-state-hash edited)
    (let ((before (t40-facts edited)))
      (dolist (case (list (list (list :state edited :provenance "hand edit, unsettled") "not a propagation fixed point")
                          (list (list :state *start-state*) "provenance missing")
                          (list (list :state *start-state* :provenance "") "provenance missing")
                          (list (list :state nil :provenance "none") "missing problem-state")))
        (let ((result (beam-crossing-scenario-result (first case))))
          (t40-check (list "unresolved" (second case))
                     (and (eq :unresolved (getf result :status)) (search (second case) (getf result :reason))
                          (null (getf result :beams))))))
      (t40-check "unsettled caller state unchanged" (equal before (t40-facts edited)))
      (t40-check "unresolved report prints only the reason"
                 (let ((text (t40-text #'report-beam-crossing-scenario (list :state edited :provenance "x"))))
                   (and (search "UNRESOLVED" text) (not (search "active crossings" text))))))))

(defun t40-run-checks ()
  (setf *t40-count* 0)
  (let ((before (t40-facts *start-state*)))
    (t40-static-checks)
    (t40-inactive-checks)
    (t40-shield-checks)
    (t40-gate-checks)
    (t40-unresolved-checks)
    (t40-check "start state unchanged" (equal before (t40-facts *start-state*))))
  (format t "~&T40 CHECKS PASSED: ~D~%" *t40-count*))
