;;; T41 focused checks; stage the problem and load tech/constraint-profile.lisp first.
;;; Corner: (t41-run-corner-checks).  Windtunnel: (t41-run-windtunnel-checks).
;;; No search.  Reference states replay prefixes of the validated corner and windtunnel
;;; traces, plus two short replayed corner variants (walk, then pickup).  Fixtures are
;;; hand-edited arrangements settled by the engine's own propagation before evaluation.
(in-package :ww)
(defvar *t41-count* 0)
(defun t41-check (label value)
  (assert value () "T41 failed: ~A" label)
  (incf *t41-count*)
  (format t "~&PASS ~A~%" label))
(defun t41-text (function &rest arguments)
  (with-output-to-string (*standard-output*) (apply function arguments)))
(defun t41-facts (state)
  (sort (mapcar #'prin1-to-string (list-database (problem-state.idb state))) #'string<))
(defun t41-replay (actions label)
  (let ((validation (validate-action-sequence *start-state* actions)))
    (t41-check (list "reference sequence replays" label) (action-sequence-validation-success-p validation))
    (action-sequence-validation-final-state validation)))
(defun t41-corner-actions ()
  (load (merge-pathnames "doc/problems/corner-topo/constraint-evidence/full-path/candidate-actions.lisp"
                         (asdf:system-source-directory :wouldwork)))
  (symbol-value '*corner-topo-candidate*))
(defun t41-prefix (count)
  (t41-replay (subseq (t41-corner-actions) 0 count) (list "corner prefix" count)))
(defun t41-settled-fixture (add)
  (let ((state (copy-problem-state *start-state*)))
    (dolist (fact add) (add-proposition fact (problem-state.idb state)))
    (invalidate-problem-state-hash state)
    (let ((*applying-init-action* nil))
      (funcall (symbol-function 'propagate-changes!) state))
    (t41-check (list "fixture settles consistently" add) (not (state-is-inconsistent state)))
    state))
(defun t41-record (result relay)
  (assoc relay (getf result :relays)))
(defun t41-link (result owner other)
  (find-if (lambda (link) (and (eq (getf link :owner) owner) (eq (getf link :other) other)))
           (getf result :links)))
(defun t41-direction (result owner other from)
  (find from (getf (t41-link result owner other) :directions) :key (lambda (d) (getf d :from))))
(defun t41-receiver (result receiver)
  (find receiver (getf result :receivers) :key (lambda (entry) (getf entry :receiver))))
(defun t41-feeder (result receiver relay)
  (find relay (getf (t41-receiver result receiver) :feeders) :key (lambda (f) (getf f :relay))))
(defun t41-agreement (state result)
  "Engine agreement flags, decomposed link readings, and independent engine lighting."
  (let* ((selector (when (eq (getf result :view) :recording)
                     (funcall (symbol-function 'recording-shadow-view-object) state)))
         (active (unless selector (funcall (symbol-function 'current-crossing-set) state)))
         (lighting (funcall (symbol-function 'compute-relay-lighting-for-object) state selector active)))
    (t41-check (list "lighting agreement" (getf result :provenance)) (getf result :lighting-agreement))
    (t41-check (list "color agreement" (getf result :provenance)) (getf result :color-agreement))
    (t41-check (list "receiver agreement" (getf result :provenance)) (getf result :receiver-agreement))
    (dolist (record (getf result :relays))
      (let ((engine (assoc (first record) lighting)))
        (t41-check (list "relay lit iff engine lit, same hue and layer" (first record))
                   (if (eq (fourth record) :lit)
                     (equal engine (list (first record) (fifth record) (second record)))
                     (null engine)))))
    (dolist (link (getf result :links))
      (dolist (direction (getf link :directions))
        (t41-check (list "no unexplained outcome" (getf direction :from) (getf direction :to))
                   (not (search "UNEXPLAINED" (getf direction :outcome))))
        (when (getf direction :sight)
          (t41-check (list "engine clear = sight and uncut" (getf direction :from) (getf direction :to))
                     (eq (getf direction :engine-clear)
                         (not (getf direction :cut)))))))
    (dolist (entry (getf result :receivers))
      (t41-check (list "stored status iff some feeder delivers or direct" (getf entry :receiver))
                 (eq (getf entry :stored)
                     (or (getf entry :direct)
                         (some (lambda (f) (string= "DELIVERS" (getf f :verdict))) (getf entry :feeders))))))))
(defun t41-result (state provenance &rest options)
  (let* ((before (t41-facts state))
         (result (relay-lighting-scenario-result (append (list :state state :provenance provenance) options))))
    (t41-check (list "caller state unchanged" provenance) (equal before (t41-facts state)))
    (t41-check (list "evaluated" provenance) (eq :evaluated (getf result :status)))
    (t41-agreement state result)
    result))

(defun t41-static-checks ()
  (let ((text (t41-text #'report-mechanic-coverage))
        (stations (relay-chain-stations *start-state*)))
    (t41-check "beam-relay is a contract" (search "beam-relay        COVERED    contract" text))
    (t41-check "corner zero UNCOVERED" (search "UNCOVERED (0):" text))
    (t41-check "contract beam-relay printed" (search "contract beam-relay" text))
    (t41-check "capacity row" (search "capacity: 3 outgoing pairings per connector" text))
    (t41-check "no start links" (search "start-state links (0 stored pairings): none" text))
    (t41-check "three competing stations" (search "(4 with a visible transmitter; 3 COMPETING HUES)" text))
    (t41-check "compose note" (search "not claimed to compose" text))
    (multiple-value-bind (open-state closed-states) (relay-chain-gate-states (census-type-instances 'gate))
      (let ((links (relay-chain-endpoint-links stations open-state closed-states)))
        (dolist (station stations)
          (let ((expected (sort (loop for link in links
                                      when (and (equal (first link) station)
                                                (member (second link) (census-type-instances 'transmitter)))
                                        collect (list (second link) (third link)))
                                #'string< :key #'prin1-to-string))
                (reported (sort (loop for group in (relay-light-station-feeds station links)
                                      append (copy-list (rest group)))
                                #'string< :key #'prin1-to-string)))
            (t41-check (list "station feeds reproduce RC hops" station) (equal expected reported))))))
    (t41-check "location4 red needs gate1" (search "location4@1: red transmitter1 requires open gate1" text))))

(defun t41-arrival-checks ()
  (let* ((state (t41-prefix 14))
         (result (t41-result state "corner prefix 14" :chains '((transmitter1 connector3 connector1 receiver1))
                             :phase :ordinary)))
    (t41-check "p14 crossing7 active" (equal '(crossing7) (getf result :active)))
    (t41-check "p14 direct blue link cut, not clear"
               (let ((d (t41-direction result 'connector1 'transmitter2 'transmitter2)))
                 (and (getf d :sight) (getf d :cut) (string= "NOT CLEAR" (getf d :outcome)))))
    (t41-check "p14 connector3 red in layer 1" (equal '(connector3 1 ((transmitter1 red)) :lit red)
                                                      (t41-record result 'connector3)))
    (t41-check "p14 connector1 red in layer 2 from connector3"
               (equal '(connector1 2 ((connector3 red)) :lit red) (t41-record result 'connector1)))
    (t41-check "p14 relayed red delivered"
               (string= "DELIVERED red" (getf (t41-direction result 'connector3 'connector1 'connector3) :outcome)))
    (t41-check "p14 receiver1 active, delivered"
               (and (getf (t41-receiver result 'receiver1) :stored)
                    (string= "DELIVERS" (getf (t41-feeder result 'receiver1 'connector1) :verdict))))
    (t41-check "p14 receiver3 wrong hue" (string= "WRONG HUE" (getf (t41-feeder result 'receiver3 'connector1) :verdict)))
    (t41-check "p14 connector2 unreached, its feed cut"
               (and (eq :unreached (fourth (t41-record result 'connector2)))
                    (getf (t41-direction result 'connector2 'transmitter1 'transmitter1) :cut)))
    (t41-check "p14 T33 chain clear physically"
               (eq :clear (getf (first (getf (first (getf result :chains)) :chains)) :status)))
    (t41-check "p14 T33 recording unresolved"
               (eq :unresolved (getf (second (getf result :chains)) :status))))
  (let* ((state (t41-prefix 15))
         (result (t41-result state "corner prefix 15" :chains '((transmitter1 connector3 connector1 receiver1))
                             :phase :ordinary)))
    (t41-check "p15 no active crossing" (null (getf result :active)))
    (t41-check "p15 connector1 blue in layer 1" (equal '(connector1 1 ((transmitter2 blue)) :lit blue)
                                                       (t41-record result 'connector1)))
    (t41-check "p15 connector3 red later ignored at connector1"
               (string= "IGNORED red (target settled in layer 1)"
                        (getf (t41-direction result 'connector3 'connector1 'connector3) :outcome)))
    (t41-check "p15 receiver1 dark (wrong hue), receiver3 active"
               (and (not (getf (t41-receiver result 'receiver1) :stored))
                    (string= "WRONG HUE" (getf (t41-feeder result 'receiver1 'connector1) :verdict))
                    (getf (t41-receiver result 'receiver3) :stored)))
    (t41-check "p15 connector2 absent (held)" (eq :absent (fourth (t41-record result 'connector2))))
    (t41-check "p15 T33 chain blocked"
               (eq :blocked (getf (first (getf (first (getf result :chains)) :chains)) :status)))))

(defun t41-conflict-checks ()
  (let* ((state (t41-settled-fixture '((paired connector2 transmitter1) (paired connector2 transmitter2)
                                       (paired connector2 receiver3) (paired connector3 connector2))))
         (result (t41-result state "fixture: connector2 paired to both hues")))
    (t41-check "conflict in layer 1, dark"
               (let ((record (t41-record result 'connector2)))
                 (and (eql 1 (second record)) (eq :conflict (fourth record))
                      (null (set-exclusive-or '(red blue) (mapcar #'second (third record)))))))
    (t41-check "both hues delivered into the conflict"
               (and (string= "DELIVERED red" (getf (t41-direction result 'connector2 'transmitter1 'transmitter1) :outcome))
                    (string= "DELIVERED blue" (getf (t41-direction result 'connector2 'transmitter2 'transmitter2) :outcome))))
    (t41-check "dark relay feeds nothing downstream"
               (and (eq :unreached (fourth (t41-record result 'connector3)))
                    (string= "SOURCE DARK" (getf (t41-direction result 'connector3 'connector2 'connector2) :outcome))))
    (t41-check "receiver3 link DARK, inactive"
               (and (string= "DARK" (getf (t41-feeder result 'receiver3 'connector2) :verdict))
                    (not (getf (t41-receiver result 'receiver3) :stored))))
    (t41-check "report prints CONFLICT" (search "CONFLICT (" (t41-text #'report-relay-lighting-scenario
                                                                         (list :state state :provenance "fixture"))))))

(defun t41-persistence-checks ()
  (let* ((state7 (t41-prefix 7)) (result7 (t41-result state7 "corner prefix 7")))
    (t41-check "p7 connector1 owns two pairings" (and (t41-link result7 'connector1 'transmitter1)
                                                      (t41-feeder result7 'receiver1 'connector1))))
  (let* ((state (t41-prefix 8)) (result (t41-result state "corner prefix 8")))
    (t41-check "p8 gate1 closed" (not (member '(open gate1) (list-database (problem-state.idb state)) :test #'equal)))
    (t41-check "p8 pickup cleared connector1's pairings"
               (and (null (t41-link result 'connector1 'transmitter1)) (null (t41-feeder result 'receiver1 'connector1))
                    (equal '(connector1 0 0 nil) (assoc 'connector1 (getf result :capacity)))))
    (t41-check "p8 connector2 pairing persists through the blocked beam"
               (let ((d (t41-direction result 'connector2 'transmitter1 'transmitter1)))
                 (and d (not (getf d :sight)) (string= "NOT CLEAR" (getf d :outcome))
                      (eq :unreached (fourth (t41-record result 'connector2)))))))
  (let* ((prefix (subseq (t41-corner-actions) 0 13))
         (walk '(move agent1 ((walk location3 nil location2))))
         (state (t41-replay (append prefix (list walk '(pickup-connector > agent1 picks up connector1 at location2)))
                            "variant: prefix 13, walk, pickup"))
         (result (t41-result state "variant pickup")))
    (t41-check "pickup removes the incoming link named by connector3"
               (and (null (t41-link result 'connector3 'connector1))
                    (equal '(connector3 2 0 nil) (assoc 'connector3 (getf result :capacity)))))
    (t41-check "held connector1 absent" (eq :absent (fourth (t41-record result 'connector1)))))
  (let* ((prefix (subseq (t41-corner-actions) 0 13))
         (walk '(move agent1 ((walk location3 nil location2))))
         (state (t41-replay (append prefix (list walk '(pickup-connector-retaining-pairings > agent1 picks up connector1
                                                        retaining pairings at location2)))
                            "variant: prefix 13, walk, retaining pickup"))
         (result (t41-result state "variant retaining pickup")))
    (t41-check "retaining pickup keeps owned and incoming links"
               (and (t41-link result 'connector3 'connector1) (t41-link result 'connector1 'transmitter2)
                    (equal '(connector1 3 1 nil) (assoc 'connector1 (getf result :capacity)))))
    (t41-check "retained links end at an absent endpoint"
               (and (eq :absent (fourth (t41-record result 'connector1)))
                    (string= "ENDPOINT ABSENT" (getf (t41-direction result 'connector3 'connector1 'connector3) :outcome))))
    (t41-check "receiver1 dark while connector1 is held" (not (getf (t41-receiver result 'receiver1) :stored)))))

(defun t41-capacity-checks ()
  (let ((result (t41-result (t41-prefix 13) "corner prefix 13")))
    (t41-check "p13 connector1 at capacity with one incoming"
               (equal '(connector1 3 1 nil) (assoc 'connector1 (getf result :capacity)))))
  (let* ((state (t41-settled-fixture '((paired connector1 transmitter1) (paired connector1 transmitter2)
                                       (paired connector1 receiver1) (paired connector1 receiver2))))
         (result (t41-result state "fixture: four outgoing")))
    (t41-check "four outgoing is over capacity" (equal '(connector1 4 0 t) (assoc 'connector1 (getf result :capacity))))
    (t41-check "report prints OVER CAPACITY"
               (search "OVER CAPACITY" (t41-text #'report-relay-lighting-scenario (list :state state :provenance "fixture"))))))

(defun t41-unresolved-checks ()
  (let ((unsettled (copy-problem-state *start-state*)))
    (add-proposition '(paired connector1 transmitter1) (problem-state.idb unsettled))
    (invalidate-problem-state-hash unsettled)
    (let ((before (t41-facts unsettled)))
      (dolist (entry (list (list (list :state unsettled :provenance "hand edit") "not a propagation fixed point")
                           (list (list :state *start-state*) "state provenance missing")
                           (list (list :state *start-state* :provenance "") "state provenance missing")
                           (list (list :provenance "no state") "missing problem-state")
                           (list (list :state *start-state* :provenance "bad view" :view :ghost) "view must be")
                           (list (list :state *start-state* :provenance "recording" :view :recording)
                                 "recorder technology not spliced")))
        (let ((result (relay-lighting-scenario-result (first entry))))
          (t41-check (list "unresolved" (second entry))
                     (and (eq :unresolved (getf result :status)) (search (second entry) (getf result :reason))))))
      (t41-check "unresolved report prints only the reason"
                 (let ((text (t41-text #'report-relay-lighting-scenario (list :state unsettled :provenance "hand edit"))))
                   (and (search "UNRESOLVED:" text) (not (search "relays by" text)))))
      (t41-check "unsettled caller state unchanged" (equal before (t41-facts unsettled))))))

(defun t41-run-corner-checks ()
  (setf *t41-count* 0)
  (let ((start (t41-facts *start-state*)))
    (t41-static-checks)
    (t41-arrival-checks)
    (t41-conflict-checks)
    (t41-persistence-checks)
    (t41-capacity-checks)
    (t41-unresolved-checks)
    (let ((result (t41-result (copy-problem-state *start-state*) "corner start")))
      (t41-check "start: every connector unreached" (every (lambda (r) (eq :unreached (fourth r))) (getf result :relays))))
    (t41-check "start state unchanged" (equal start (t41-facts *start-state*))))
  (format t "~&T41 CORNER CHECKS PASSED: ~D~%" *t41-count*))

(defun t41-windtunnel-actions ()
  (with-open-file (stream (merge-pathnames "doc/problems/windtunnel-topo/validate-proposed-trace.lisp"
                                           (asdf:system-source-directory :wouldwork)))
    (let ((*package* (find-package :ww)))
      (loop for form = (read stream nil :eof)
            until (eq form :eof)
            when (and (consp form) (eq (first form) 'defparameter)
                      (eq (second form) '*windtunnel-proposed-actions*))
              return (second (third form))))))

(defun t41-run-windtunnel-checks ()
  (setf *t41-count* 0)
  (let* ((start (t41-facts *start-state*))
         (actions (t41-windtunnel-actions))
         (state (t41-replay actions "windtunnel validated trace"))
         (physical (t41-result state "windtunnel final state" :view :physical))
         (recording (t41-result state "windtunnel final state" :view :recording)))
    (t41-check "17 actions" (= 17 (length actions)))
    (t41-check "cycle open" (member '(recording-in-progress) (list-database (problem-state.idb state)) :test #'equal))
    (t41-check "views labelled" (and (eq :physical (getf physical :view)) (eq :recording (getf recording :view))))
    (t41-check "recording view has no crossing set" (null (getf recording :active)))
    (t41-check "views differ in lighting" (not (equal (getf physical :relays) (getf recording :relays))))
    (let ((early (t41-replay (subseq actions 0 0) "windtunnel start")))
      (t41-check "recording without an open cycle is unresolved"
                 (search "no open recording cycle"
                         (getf (relay-lighting-scenario-result (list :state early :provenance "start" :view :recording))
                               :reason))))
    (t41-check "windtunnel MC beam-relay contract"
               (search "beam-relay        COVERED    contract" (t41-text #'report-mechanic-coverage)))
    (t41-check "start state unchanged" (equal start (t41-facts *start-state*))))
  (format t "~&T41 WINDTUNNEL CHECKS PASSED: ~D~%" *t41-count*))
