;;; Isolated regression evidence. From the repository root, create .s4-check, run
;;; sbcl --noinform --no-userinit --no-sysinit --script <this-file>, then remove .s4-check.
;;; Does not stage Wouldwork, run an extractor, or consult predictions.
(require :asdf)
(defpackage :s4-profile-checks (:use :cl))
(in-package :s4-profile-checks)
(defun ?varp (x) (and (symbolp x) (find (char (symbol-name x) 0) "?$")))
(defparameter *checks* 0)
(defun check (condition)
  (incf *checks*)
  (assert condition))
(with-open-file (in "tech/constraint-profile.lisp")
  (loop for form = (read in nil :end) until (eq form :end)
        when (and (consp form) (eq (first form) 'defun)
                  (member (second form)
                    '(keeper-sorted-set keeper-pressure-clauses keeper-mandatory-plates
                      keeper-row-avoids-p keeper-row-next keeper-reachable keeper-spine
                      keeper-fact-value keeper-goal-destinations keeper-plate-side
                      keeper-required-devices quotient-row-doors
                      quotient-reachable-door-sets quotient-row-composition)))
          do (eval form)))
;; Alternative controls do not accumulate simultaneous demand.
(check (equal (keeper-pressure-clauses '(controls ((p q) (p r)) d normal) '(p q r))
              '((p q) (p r))))
(check (equal (keeper-mandatory-plates '((p q) (p r))) '(p)))
(check (null (keeper-mandatory-plates '((p) nil))))
(check (equal (keeper-pressure-clauses '(controls (nil) d normal) '(p)) '(nil)))
(check (null (keeper-pressure-clauses '(controls nil d normal) '(p))))
(check (null (keeper-pressure-clauses '(controls ((p)) d inverted) '(p))))
;; Removal respects alternatives, empty clauses and directedness.
(let* ((door '("A" "B" walking ((d)) :both 1))
       (return '("B" "A" climbing ((ladder)) :forward 1))
       (rows (list door return)))
  (check (equal (keeper-reachable "A" rows 'd) '("A")))
  (check (equal (keeper-reachable "B" rows 'd) '("A" "B")))
  (check (equal (keeper-reachable "A" rows nil) '("A" "B")))
  (check (eq :both (keeper-plate-side "A" '("A") '("A" "B"))))
  (check (eq :approach-only (keeper-plate-side "B" '("A" "B") '("A"))))
  (check (eq :departure-only (keeper-plate-side "B" '("A") '("A" "B"))))
  (check (eq :neither (keeper-plate-side "C" '("A") '("B"))))
  (check (eq :unlocated (keeper-plate-side nil '("A") '("B"))))
  (check (equal (keeper-required-devices "A" "B" rows '(d other)) '(d)))
  (check (null (keeper-required-devices "B" "A" rows '(d other))))
  (check (null (nth-value 1 (keeper-required-devices "A" "C" rows '(d)))))
  (multiple-value-bind (spine reason) (keeper-spine rows '("A" "B") '(d))
    (check (null reason)) (check (= 2 (length spine)))))
(check (keeper-row-avoids-p '("A" "B" walking ((d) (e)) :both 1) 'd))
(check (keeper-row-avoids-p '("A" "B" walking (nil) :both 1) 'd))
(check (keeper-row-avoids-p '("A" "B" walking nil :forward 1) 'd))
(check (eq :alternative-families
           (nth-value 1 (keeper-spine '(("A" "B" walking ((d) (e)) :both 1))
                                      '("A" "B") '(d e)))))
;; A closure triangle retains its true two-link spine.
(let ((rows '(("A" "B" walking ((d)) :both 1)
              ("B" "C" walking ((e)) :both 1)
              ("A" "C" walking ((d e)) :both 1))))
  (multiple-value-bind (spine reason) (keeper-spine rows '("A" "B" "C") '(d e))
    (check (null reason)) (check (= 2 (length spine)))))
;; Simultaneously dropping redundant edges must not manufacture cuts.
(let ((rows '(("A" "B" walking ((d)) :both 1)
              ("B" "C" walking ((d)) :both 1)
              ("A" "C" walking ((d)) :both 1))))
  (check (eq :reachability-mismatch
             (first (nth-value 1 (keeper-spine rows '("A" "B" "C") '(d)))))))
;; A negative/disjunctive/quantified target is not an obligatory destination.
(multiple-value-bind (destinations unresolved)
    (keeper-goal-destinations '(and (has-location actor target)
                                    (not (has-location cargo elsewhere))
                                    (or (has-location x here) (has-location x there))
                                    (has-location ?actor target)))
  (check (equal destinations '((has-location actor target))))
  (check (= 3 (length unresolved))))
(check (null (keeper-goal-destinations '(exists (?a agent) (has-location ?a target)))))
(check (equal (keeper-fact-value 'has-position 'p '((has-position p l))) 'l))
(defparameter *writer-fails* nil)
(defun report-static-constraint-profile ()
  (if *writer-fails* (error "Expected test generator failure") (write-line "complete")))
(with-open-file (in "tech/constraint-profile.lisp")
  (loop for form = (read in nil :end) until (eq form :end)
        when (and (consp form) (eq (first form) 'defun)
                  (eq (second form) 'write-static-constraint-profile))
          do (eval form)))
;; Relative path regression and preservation when the generator fails.
(let ((target #P".s4-check/writer-test.txt"))
  (write-static-constraint-profile target)
  (check (probe-file target))
  (write-static-constraint-profile target)
  (let ((*writer-fails* t)) (check (handler-case (progn (write-static-constraint-profile target) nil)
                                   (error () t))))
  (with-open-file (in target) (check (string= "complete" (read-line in))))
  (delete-file target))
(format t "~&S4 helper checks passed: ~D. All source forms read successfully.~%" *checks*)
